ServerEvents.recipes(event => {

    event.recipes.gtceu.macerator("kubejs:ap/monazite_rod_macerator")
        .itemInputs("architects_palette:monazite_rod")
        .chancedOutput("gtceu:monazite_ce_dust", 9500, 0)
        .chancedOutput("gtceu:monazite_dust", 7500, 0)
        .chancedOutput("gtceu:monazite_nd_dust", 4500, 0)
        .chancedOutput("gtceu:monazite_sm_dust", 2200, 0)
        .chancedOutput("gtceu:monazite_gd_dust", 1000, 0)
        .duration(400)
        .EUt(GTValues.VA[GTValues.ULV])

    event.recipes.gtceu.macerator("kubejs:ap/heliodor_rod_macerator")
        .itemInputs("architects_palette:heliodor_rod")
        .chancedOutput("gtceu:heliodor_dust", 9500, 0)
        .chancedOutput("gtceu:heliodor_dust", 7500, 0)
        .chancedOutput("gtceu:beryl_dust", 4500, 0)
        .chancedOutput("gtceu:goshenite_dust", 2200, 0)
        .chancedOutput("gtceu:emerald_dust", 1000, 0)
        .duration(400)
        .EUt(GTValues.VA[GTValues.ULV])

    event.recipes.gtceu.macerator("kubejs:ap/ekanite_rod_macerator")
        .itemInputs("architects_palette:ekanite_rod")
        .chancedOutput("gtceu:ekanite_dust", 9500, 0)
        .chancedOutput("gtceu:ekanite_dust", 7500, 0)
        .chancedOutput("gtceu:ekanite_dust", 4500, 0)
        .chancedOutput("gtceu:thorite_dust", 2200, 0)
        .chancedOutput("gtceu:thorianite_dust", 1000, 0)
        .duration(400)
        .EUt(GTValues.VA[GTValues.ULV])
})