ServerEvents.recipes(event => {
    event.replaceInput({id:"immersive_melodies:lute"}, "#minecraft:planks", "gtceu:wood_plate")
    event.replaceInput({id:"immersive_melodies:lute"}, "minecraft:stick", "gtceu:long_wood_rod")
    event.replaceInput({id:"immersive_melodies:flute"}, "minecraft:stick", "gtceu:wood_small_fluid_pipe")
    event.replaceInput({id:"immersive_melodies:handpan"}, "minecraft:copper_ingot", "gtceu:copper_plate")
    event.replaceInput({id:"immersive_melodies:handpan"}, "minecraft:copper_block", "gtceu:double_copper_plate")
    event.replaceInput({id:"immersive_melodies:triangle"}, "minecraft:copper_ingot", "gtceu:brass_rod")
    event.replaceInput({id:"immersive_melodies:didgeridoo"}, "minecraft:lapis_lazuli", "#forge:dyes/blue")
    event.replaceInput({id:"immersive_melodies:didgeridoo"}, "#minecraft:planks", "gtceu:wood_normal_fluid_pipe")
    event.replaceInput({id:"immersive_melodies:vielle"}, "#minecraft:logs", "gtceu:treated_wood_plate")
    event.replaceInput({id:"immersive_melodies:vielle"}, "minecraft:stick", "gtceu:treated_wood_rod")
    event.replaceInput({id:"immersive_melodies:trumpet"}, "minecraft:copper_ingot", "gtceu:brass_rod")
    event.replaceInput({id:"immersive_melodies:trumpet"}, "minecraft:iron_ingot", "gtceu:brass_plate")
})