ServerEvents.recipes(event => {
    // Crystal Clusters
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_ruby_crystal")
        .itemInputs("infinite_abyss:ruby_crystal")
        .itemOutputs("3x gtceu:ruby_gem")
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_golden_topaz_crystal")
        .itemInputs("infinite_abyss:golden_topaz_crystal")
        .itemOutputs("3x gtceu:topaz_gem")
        .chancedOutput("gtceu:blue_topaz_gem", 3500, 0)
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_emerald_crystal")
        .itemInputs("infinite_abyss:emerald_crystal")
        .itemOutputs("3x minecraft:emerald")
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_dark_amethyst_crystal")
        .itemInputs("infinite_abyss:deep_amethyst_crystal")
        .itemOutputs("3x minecraft:amethyst_shard", "gtceu:dark_ash_dust")
        .chancedOutput("gtceu:smoky_quartz_gem", 7500, 0)
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_ruby_crystal2")
        .itemInputs("infinite_abyss:ruby_crystal_2")
        .itemOutputs("3x gtceu:ruby_gem")
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_golden_topaz_crystal2")
        .itemInputs("infinite_abyss:golden_topaz_crystal_2")
        .itemOutputs("3x gtceu:topaz_gem")
        .chancedOutput("gtceu:blue_topaz_gem", 3500, 0)
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_emerald_crystal2")
        .itemInputs("infinite_abyss:emerald_crystal_2")
        .itemOutputs("3x minecraft:emerald")
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_dark_amethyst_crystal2")
        .itemInputs("infinite_abyss:deep_amethyst_crystal_2")
        .itemOutputs("3x minecraft:amethyst_shard", "gtceu:dark_ash_dust")
        .chancedOutput("gtceu:smoky_quartz_gem", 7500, 0)
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_light_blue_crystal")
        .itemInputs("infinite_abyss:light_blue_crystal")
        .itemOutputs("2x gtceu:blue_opal_gem", "1x ae2:certus_quartz_crystal")
        .chancedOutput("1x gtceu:charged_certus_quartz_gem", 2500, 0)
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_light_blue_crystal_2")
        .itemInputs("infinite_abyss:light_blue_downwards_crystal")
        .itemOutputs("2x gtceu:blue_opal_gem", "1x ae2:certus_quartz_crystal")
        .chancedOutput("1x gtceu:charged_certus_quartz_gem", 2500, 0)
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])

    // Glowing gems
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_glowing_green_crystal")
        .itemInputs("infinite_abyss:green_glowing_crystal")
        .chancedOutput("gtceu:uvarovite_gem", 8500, 0)
        .chancedOutput("gtceu:knorringite_gem", 5500, 0)
        .chancedOutput("gtceu:ekanite_gem", 2500, 0)
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_glowing_green_crystal_block")
        .itemInputs("infinite_abyss:glowing_green_crystal_block")
        .chancedOutput("4x gtceu:uvarovite_gem", 8500, 0)
        .chancedOutput("4x gtceu:knorringite_gem", 5500, 0)
        .chancedOutput("4x gtceu:ekanite_gem", 2500, 0)
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_glowing_pink_crystal")
        .itemInputs("infinite_abyss:pink_glowing_crystal")
        .chancedOutput("gtceu:diaspore_gem", 8500, 0)
        .chancedOutput("gtceu:rose_quartz_gem", 5500, 0)
        .chancedOutput("gtceu:chiolite_gem", 2500, 0)
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_glowing_pink_crystal_block")
        .itemInputs("infinite_abyss:glowing_pink_crystal")
        .chancedOutput("4x gtceu:diaspore_gem", 8500, 0)
        .chancedOutput("4x gtceu:rose_quartz_gem", 5500, 0)
        .chancedOutput("4x gtceu:chiolite_gem", 2500, 0)
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_glowing_red_crystal")
        .itemInputs("infinite_abyss:red_glowing_crystal")
        .chancedOutput("gtceu:spinel_gem", 8500, 0)
        .chancedOutput("gtceu:pyrope_gem", 5500, 0)
        .chancedOutput("gtceu:rhodochrosite_gem", 2500, 0)
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_glowing_red_crystal_block")
        .itemInputs("infinite_abyss:glowing_red_crystal")
        .chancedOutput("4x gtceu:spinel_gem", 8500, 0)
        .chancedOutput("4x gtceu:pyrope_gem", 5500, 0)
        .chancedOutput("4x gtceu:rhodochrosite_gem", 2500, 0)
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_glowing_blue_crystal")
        .itemInputs("infinite_abyss:blue_glowing_crystal")
        .chancedOutput("gtceu:azurite_gem", 8500, 0)
        .chancedOutput("gtceu:vauxite_gem", 5500, 0)
        .chancedOutput("gtceu:hauyne_gem", 2500, 0)
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_glowing_yellow_crystal")
        .itemInputs("infinite_abyss:yellow_glowing_crystal")
        .chancedOutput("gtceu:pyromorphite_gem", 8500, 0)
        .chancedOutput("gtceu:bismutite_gem", 5500, 0)
        .chancedOutput("gtceu:dreyerite_gem", 2500, 0)
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_fire_crystal_block")
        .itemInputs("infinite_abyss:fire_crystal")
        .chancedOutput("4x gtceu:vanadinite_gem", 8500, 0)
        .chancedOutput("4x gtceu:minium_gem", 5500, 0)
        .chancedOutput("4x gtceu:crocoite_gem", 2500, 0)
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_light_blue_crystal_block")
        .itemInputs("infinite_abyss:light_blue_crystal_block")
        .chancedOutput("4x gtceu:celestine_gem", 8500, 0)
        .chancedOutput("4x gtceu:aquamarine_gem", 5500, 0)
        .chancedOutput("4x gtceu:uranocircite_gem", 2500, 0)
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])

    // Handling the weird cut gems
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_rough_red_crystal")
        .itemInputs("infinite_abyss:rough_red_crystal")
        .chancedOutput("gtceu:spinel_gem", 8500, 0)
        .chancedOutput("gtceu:pyrope_gem", 5500, 0)
        .chancedOutput("gtceu:rhodochrosite_gem", 2500, 0)
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_cut_red_crystal")
        .itemInputs("infinite_abyss:cut_red_crystal")
        .chancedOutput("2x gtceu:spinel_gem", 8500, 0)
        .chancedOutput("2x gtceu:pyrope_gem", 5500, 0)
        .chancedOutput("2x gtceu:rhodochrosite_gem", 2500, 0)
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_flawless_red_crystal")
        .itemInputs("infinite_abyss:flawless_red_crystal")
        .chancedOutput("4x gtceu:spinel_gem", 8500, 0)
        .chancedOutput("4x gtceu:pyrope_gem", 5500, 0)
        .chancedOutput("4x gtceu:rhodochrosite_gem", 2500, 0)
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_perfect_red_crystal")
        .itemInputs("infinite_abyss:perfect_red_crystal")
        .chancedOutput("8x gtceu:spinel_gem", 8500, 0)
        .chancedOutput("8x gtceu:pyrope_gem", 5500, 0)
        .chancedOutput("8x gtceu:rhodochrosite_gem", 2500, 0)
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_rough_light_blue_crystal")
        .itemInputs("infinite_abyss:rough_light_blue_crystal")
        .chancedOutput("gtceu:celestine_gem", 8500, 0)
        .chancedOutput("gtceu:aquamarine_gem", 5500, 0)
        .chancedOutput("gtceu:uranocircite_gem", 2500, 0)
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_cut_light_blue_crystal")
        .itemInputs("infinite_abyss:cut_light_blue_crystal")
        .chancedOutput("2x gtceu:celestine_gem", 8500, 0)
        .chancedOutput("2x gtceu:aquamarine_gem", 5500, 0)
        .chancedOutput("2x gtceu:uranocircite_gem", 2500, 0)
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])
    event.recipes.gtceu.macerator("kubejs:infabyss/macerate_flawless_light_blue_crystal")
        .itemInputs("infinite_abyss:flawless_light_blue_crystal")
        .chancedOutput("4x gtceu:celestine_gem", 8500, 0)
        .chancedOutput("4x gtceu:aquamarine_gem", 5500, 0)
        .chancedOutput("4x gtceu:uranocircite_gem", 2500, 0)
        .duration(120)
        .EUt(GTValues.VA[GTValues.ULV])

    event.recipes.gtceu.laser_engraver("kubejs:infabyss/engrave_red_crystal_to_cut")
        .itemInputs("2x infinite_abyss:rough_red_crystal")
        .notConsumable("#forge:lenses/white")
        .itemOutputs("1x infinite_abyss:cut_red_crystal")
        .duration(300)
        .EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.laser_engraver("kubejs:infabyss/engrave_red_crystal_to_flawless")
        .itemInputs("2x infinite_abyss:cut_red_crystal")
        .notConsumable("#forge:lenses/white")
        .itemOutputs("1x infinite_abyss:flawless_red_crystal")
        .duration(300)
        .EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.laser_engraver("kubejs:infabyss/engrave_red_crystal_to_perfect")
        .itemInputs("2x infinite_abyss:flawless_red_crystal")
        .notConsumable("#forge:lenses/white")
        .itemOutputs("1x infinite_abyss:perfect_red_crystal")
        .duration(300)
        .EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.cutter("kubejs:infabyss/cut_red_crystal_to_flawless")
        .itemInputs("1x infinite_abyss:perfect_red_crystal")
        .itemOutputs("2x infinite_abyss:flawless_red_crystal")
        .duration(30)
        .EUt(GTValues.VHA[GTValues.LV])
    event.recipes.gtceu.cutter("kubejs:infabyss/cut_red_crystal_to_cut")
        .itemInputs("1x infinite_abyss:flawless_red_crystal")
        .itemOutputs("2x infinite_abyss:cut_red_crystal")
        .duration(30)
        .EUt(GTValues.VHA[GTValues.LV])
    event.recipes.gtceu.cutter("kubejs:infabyss/cut_red_crystal_to_rough")
        .itemInputs("1x infinite_abyss:cut_red_crystal")
        .itemOutputs("2x infinite_abyss:rough_red_crystal")
        .duration(30)
        .EUt(GTValues.VHA[GTValues.LV])

    event.recipes.gtceu.laser_engraver("kubejs:infabyss/engrave_light_blue_crystal_to_cut")
        .itemInputs("2x infinite_abyss:rough_light_blue_crystal")
        .notConsumable("#forge:lenses/white")
        .itemOutputs("1x infinite_abyss:cut_light_blue_crystal")
        .duration(300)
        .EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.laser_engraver("kubejs:infabyss/engrave_light_blue_crystal_to_flawless")
        .itemInputs("2x infinite_abyss:cut_light_blue_crystal")
        .notConsumable("#forge:lenses/white")
        .itemOutputs("1x infinite_abyss:flawless_light_blue_crystal")
        .duration(300)
        .EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.cutter("kubejs:infabyss/cut_light_blue_crystal_to_cut")
        .itemInputs("1x infinite_abyss:flawless_light_blue_crystal")
        .itemOutputs("2x infinite_abyss:cut_light_blue_crystal")
        .duration(30)
        .EUt(GTValues.VHA[GTValues.LV])
    event.recipes.gtceu.cutter("kubejs:infabyss/cut_light_blue_crystal_to_rough")
        .itemInputs("1x infinite_abyss:cut_light_blue_crystal")
        .itemOutputs("2x infinite_abyss:rough_light_blue_crystal")
        .duration(30)
        .EUt(GTValues.VHA[GTValues.LV])
})