ServerEvents.recipes(event => {
    
    // Rod and parts
    event.remove({id: "starcatcher:rod_from_vanilla"})
    event.replaceInput({id:"starcatcher:starcatcher_rod"}, "minecraft:stick", "gtceu:treated_wood_rod")
    event.replaceInput({id:"starcatcher:hook"}, "minecraft:iron_nugget", "gtceu:iron_ring")
    event.replaceInput({id:"starcatcher:hook"}, "minecraft:iron_ingot", "gtceu:iron_rod")
    event.replaceInput({id:"starcatcher:bobber"}, "minecraft:stick", "gtceu:iron_rod")
    event.replaceInput({id:"starcatcher:bobber"}, "#minecraft:planks", "gtceu:treated_wood_plate")

    // Fish Oil
    event.recipes.gtceu.extractor("kubejs:fish_extraction")
        .itemInputs("#minecraft:fishes")
        .outputFluids("gtceu:fish_oil 50")
        .duration(0.8*20)
        .EUt(GTValues.VHA[GTValues.ULV])

    // Shrine generation
    function shrineReward(fish, tier, mainOutput, secondOutput, bonus) {
        if (tier <= 1) {
            const fih = event.recipes.gtceu.fish_shrine(`kubejs:starcatcher/shrine_${fish}_tier_1`)
            fih.notConsumable("starcatcher:trophy_copper")
            fih.chancedInput(`starcatcher:${fish}`, (tier/1)*100, 0)
            fih.itemOutputs(`${Math.ceil((1/tier)**2)}x ${mainOutput}`, `${Math.ceil((1/tier)*2)}x ${secondOutput}`)
            fih.EUt(GTValues.VHA[GTValues.MV])
            fih.duration(3600)
            fih.inputEU(1.5*128)
            if (bonus != null) {
                fih.chancedOutput(`${bonus}`, (1/tier)*1000, 0)
            }
        }
        if (tier <= 2) {
            const fih2 = event.recipes.gtceu.fish_shrine(`kubejs:starcatcher/shrine_${fish}_tier_2`)
            fih2.notConsumable("starcatcher:trophy_iron")
            fih2.chancedInput(`starcatcher:${fish}`, (tier/2)*100, 0)
            fih2.itemOutputs(`${Math.ceil((2/tier)**2)}x ${mainOutput}`, `${Math.ceil((2/tier)*2)}x ${secondOutput}`)
            fih2.EUt(GTValues.VHA[GTValues.MV])
            fih2.duration(3600)
            fih2.inputEU(1.5*512)
            if (bonus != null) {
                fih2.chancedOutput(`${bonus}`, (2/tier)*1000, 0)
            }
        }
        if (tier <= 3) {
            const fih3 = event.recipes.gtceu.fish_shrine(`kubejs:starcatcher/shrine_${fish}_tier_3`)
            fih3.notConsumable("starcatcher:trophy_gold")
            fih3.chancedInput(`starcatcher:${fish}`, (tier/3)*100, 0)
            fih3.itemOutputs(`${Math.ceil((3/tier)**2)}x ${mainOutput}`, `${Math.ceil((3/tier)*2)}x ${secondOutput}`)
            fih3.EUt(GTValues.VHA[GTValues.MV])
            fih3.duration(3600)
            fih3.inputEU(1.5*2048)
            if (bonus != null) {
                fih3.chancedOutput(`${bonus}`, (3/tier)*1000, 0)
            }
        }
        if (tier <= 4) {
            const fih4 = event.recipes.gtceu.fish_shrine(`kubejs:starcatcher/shrine_${fish}_tier_4`)
            fih4.notConsumable("starcatcher:trophy_emerald")
            fih4.chancedInput(`starcatcher:${fish}`, (tier/4)*100, 0)
            fih4.itemOutputs(`${Math.ceil((4/tier)**2)}x ${mainOutput}`, `${Math.ceil((4/tier)*2)}x ${secondOutput}`)
            fih4.EUt(GTValues.VHA[GTValues.MV])
            fih4.duration(3600)
            fih4.inputEU(1.5*8192)
            if (bonus != null) {
                fih4.chancedOutput(`${bonus}`, (4/tier)*1000, 0)
            }
        }
        if (tier <= 5) {
            const fih5 = event.recipes.gtceu.fish_shrine(`kubejs:starcatcher/shrine_${fish}_tier_5`)
            fih5.notConsumable("starcatcher:trophy_diamond")
            fih5.chancedInput(`starcatcher:${fish}`, (tier/5)*100, 0)
            fih5.itemOutputs(`${Math.ceil((5/tier)**2)}x ${mainOutput}`, `${Math.ceil((5/tier)*2)}x ${secondOutput}`)
            fih5.EUt(GTValues.VHA[GTValues.MV])
            fih5.duration(3600)
            fih5.inputEU(1.5*8192*4)
            if (bonus != null) {
                fih5.chancedOutput(`${bonus}`, (5/tier)*1000, 0)
            }
        }
        if (tier <= 6) {
            const fih6 = event.recipes.gtceu.fish_shrine(`kubejs:starcatcher/shrine_${fish}_tier_6`)
            fih6.notConsumable("starcatcher:trophy_of_the_older_angler")
            fih6.chancedInput(`starcatcher:${fish}`, (tier/6)*100, 0)
            fih6.itemOutputs(`${Math.ceil((6/tier)**2)}x ${mainOutput}`, `${Math.ceil((6/tier)*2)}x ${secondOutput}`)
            fih6.EUt(GTValues.VHA[GTValues.MV])
            fih6.duration(3600)
            fih6.inputEU(1.5*8192*16)
            if (bonus != null) {
                fih6.chancedOutput(`${bonus}`, (6/tier)*1000, 0)
            }
        }
    }

    shrineReward("geode_eel", 2, "gtceu:manganocalcite_dust", "minecraft:amethyst_shard", "gtceu:basalt_dust")
    shrineReward("black_eel", 1, "gtceu:blackstone_dust", "minecraft:black_dye", null)
    shrineReward("obsidian_eel", 4, "minecraft:obsidian", "minecraft:crying_obsidian", "regions_unexplored:cobalt_obsidian")
    shrineReward("molten_shrimp", 2, "minecraft:magma_block", "minecraft:magma_cream", null)
    shrineReward("obsidian_crab", 3, "minecraft:obsidian", "gtceu:obsidian_dust", null)
    shrineReward("scorched_bloodsucker", 5, "undergarden:blood_globule", "minecraft:rotten_flesh", "twilightforest:fiery_blood")
    shrineReward("molten_deepslate_crab", 2, "gtceu:deepslate_dust", "gtceu:fire_opal_gem", "gtceu:small_gold_dust")
    shrineReward("cinder_squid", 3, "tconstruct:blazewood", "gtceu:small_blaze_dust", null)
    shrineReward("lava_crab", 1, "gtceu:netherrack_dust", "minecraft:quartz", "minecraft:nether_brick")
    shrineReward("chorus_crab", 2, "minecraft:chorus_fruit", "minecraft:chorus_flower", "gtceu:purpurite_dust")
    //shrineReward("obidontiee", 2, "minecraft:chorus_fruit", "minecraft:chorus_flower", "gtceu:purpurite_dust")
    shrineReward("silverveil_perch", 2, "regions_unexplored:silver_birch_branch", "gtceu:salt_dust", "gtceu:small_silver_dust")
    //shrineReward("elderscale", 2, "minecraft:chorus_fruit", "minecraft:chorus_flower", "gtceu:purpurite_dust")
    //shrineReward("driftfin", 2, "minecraft:chorus_fruit", "minecraft:chorus_flower", "gtceu:purpurite_dust")
    //shrineReward("twilight_koi", 2, "minecraft:chorus_fruit", "minecraft:chorus_flower", "gtceu:purpurite_dust")
    //shrineReward("thunder_bass", 2, "minecraft:chorus_fruit", "minecraft:chorus_flower", "gtceu:purpurite_dust")
    //shrineReward("lightning_bass", 2, "minecraft:chorus_fruit", "minecraft:chorus_flower", "gtceu:purpurite_dust")
    shrineReward("sludge_catfish", 1, "minecraft:mangrove_roots", "gtceu:bio_chaff", "minecraft:mud")
    shrineReward("lily_snapper", 1, "minecraft:lily_pad", "regions_unexplored:flowering_lily_pad", "minecraft:lily_of_the_valley")
    //shrineReward("sage_catfish", 2, "minecraft:chorus_fruit", "minecraft:chorus_flower", "gtceu:purpurite_dust")
    //shrineReward("pale_carp", 2, "minecraft:chorus_fruit", "minecraft:chorus_flower", "gtceu:purpurite_dust")
    shrineReward("pale_pinfish", 4, "minecraft:bone", "gtceu:opal_gem", "gtceu:ultimet_bolt")
    shrineReward("pinfish", 4, "minecraft:bone", "gtceu:black_opal_gem", "gtceu:dark_steel_bolt")
    shrineReward("frostjaw_trout", 3, "minecraft:snowball", "gtceu:ice_dust", "undergarden:froststeel_nugget")
    shrineReward("crystalback_trout", 5, "minecraft:cobblestone", "ae2:certus_quartz_crystal", "apotheosis:rare_material")
    shrineReward("aurora", 6, "twilightforest:aurora_block", "gtceu:vanadium_steel_dust", "gtceu:small_osmium_dust")
    shrineReward("wintery_pike", 2, "minecraft:ice", "infinite_abyss:ice_spike", "gtceu:cubo_ice_dust")
    shrineReward("sandtail", 3, "minecraft:sand", "gtceu:quartz_sand_dust", "gtceu:small_cassiterite_sand_dust")
    shrineReward("mirage_carp", 4, "minecraft:sandstone", "natures_spirit:coconut", "minecraft:emerald")
    shrineReward("scorchfish", 2, "minecraft:red_sand", "tconstruct:scorched_brick", null)
    shrineReward("cactifish", 1, "dynamictreesplus:pillar_cactus_seed", "minecraft:cactus", null)
    //shrineReward("agave_bream", 1, "dynamictreesplus:pillar_cactus_seed", "minecraft:cactus", null)
    //shrineReward("sunny_sturgeon", 1, "dynamictreesplus:pillar_cactus_seed", "minecraft:cactus", null)
    shrineReward("rockgill", 1, "minecraft:stone", "gtceu:granite_dust", "gtceu:andesite_dust")
    //shrineReward("peakdweller", 1, "dynamictreesplus:pillar_cactus_seed", "minecraft:cactus", null)
    //shrineReward("sun_seeking_carp", 1, "dynamictreesplus:pillar_cactus_seed", "minecraft:cactus", null)
    shrineReward("blossomfish", 1, "minecraft:cherry_leaves", "minecraft:stripped_cherry_wood", "dynamictrees:cherry_seed")
    shrineReward("petaldrift_carp", 1, "minecraft:pink_petals", "minecraft:cherry_wood", null)
    shrineReward("pink_koi", 3, "regions_unexplored:cherry_branch", "gtceu:pink_sapphire_dust", "gtceu:pink_diamond_dust")
    shrineReward("morganite", 4, "gtceu:morganite_gem", "gtceu:pezzottaite_cs_gem", "gtceu:small_manganese_dust")
    shrineReward("rose_siamese_fish", 5, "gtceu:rose_quartz_gem", "minecraft:rose_bush", "gtceu:rose_gold_dust")
    //shrineReward("vesani", 4, "gtceu:morganite_gem", "gtceu:pezzottaite_cs_gem", "gtceu:small_manganese_dust")
    shrineReward("crystalback_sturgeon", 5, "minecraft:cobblestone", "gtceu:charged_certus_quartz_gem", "gtceu:beryl_dust")
    //shrineReward("icetooth_sturgeon", 4, "gtceu:morganite_gem", "gtceu:pezzottaite_cs_gem", "gtceu:small_manganese_dust")
    shrineReward("boreal", 6, "minecraft:blue_ice", "gtceu:tungsten_steel_dust", "gtceu:small_ruthenium_dust")
    //shrineReward("crystalback_boreal", 4, "gtceu:morganite_gem", "gtceu:pezzottaite_cs_gem", "gtceu:small_manganese_dust")
    shrineReward("silverfin_pike", 2, "natures_spirit:silverbush", "gtceu:hydrohalite_dust", "gtceu:small_sterling_silver_dust")
    shrineReward("carpenjoe", 5, "gtceu:uraninite_dust", "gtceu:torbernite_gem", "gtceu:small_gallium_arsenide_dust")
    shrineReward("willow_bream", 4, "regions_unexplored:willow_branch", "gtceu:small_yttria_dust", "gtceu:small_praseodymia_dust")
    //shrineReward("drifting_bream", 5, "gtceu:uraninite_dust", "gtceu:torbernite_gem", "gtceu:small_gallium_arsenide_dust")
    //shrineReward("downfall_bream", 5, "gtceu:uraninite_dust", "gtceu:torbernite_gem", "gtceu:small_gallium_arsenide_dust")
    //shrineReward("hollowberry_darter", 5, "gtceu:uraninite_dust", "gtceu:torbernite_gem", "gtceu:small_gallium_arsenide_dust")
    //shrineReward("mistback_chub", 5, "gtceu:uraninite_dust", "gtceu:torbernite_gem", "gtceu:small_gallium_arsenide_dust")
    //shrineReward("bluegigi", 5, "gtceu:uraninite_dust", "gtceu:torbernite_gem", "gtceu:small_gallium_arsenide_dust")
    shrineReward("frostgill_chub", 1, "minecraft:snowball", "gtceu:small_ice_dust", null)
    shrineReward("crystalback_minnow", 2, "gtceu:quartzite_gem", "gtceu:small_amethyst_dust", null)
    shrineReward("azure_crystalback_minnow", 4, "gtceu:quartzite_gem", "gtceu:lazulite_gem", "gtceu:azurite_gem")
    //shrineReward("blue_crystal_fin", 2, "gtceu:quartzite_gem", "gtceu:small_amethyst_dust", null)
    //shrineReward("blue_herring", 2, "gtceu:quartzite_gem", "gtceu:small_amethyst_dust", null)
    shrineReward("ironjaw_herring", 2, "minecraft:granite", "gtceu:hematite_dust", "gtceu:small_iron_dust")
    shrineReward("deepjaw_herring", 2, "minecraft:kelp", "minecraft:gravel", "minecraft:prismarine_shard")
    //shrineReward("dusktail_snapper", 2, "gtceu:quartzite_gem", "gtceu:small_amethyst_dust", null)
    shrineReward("joel", 6, "minecraft:prismarine_shard", "gtceu:molybdenum_dust", "gtceu:arsenic_trioxide_dust")
    //shrineReward("redscaled_tuna", 2, "gtceu:quartzite_gem", "gtceu:small_amethyst_dust", null)
    //shrineReward("bigeye_tuna", 2, "gtceu:quartzite_gem", "gtceu:small_amethyst_dust", null)
    shrineReward("sea_bass", 1, "minecraft:dirt", "gtceu:flint_dust", "gtceu:small_carbon_dust")
    shrineReward("shroomfish", 6, "farmersdelight:red_mushroom_colony", "farmersdelight:brown_mushroom_colony", "gtceu:small_plutonium_dust")
    shrineReward("sporefish", 3, "minecraft:red_mushroom", "minecraft:brown_mushroom", "gtceu:small_strontium_dust")
    shrineReward("gold_fan", 3, "natures_spirit:marigold", "gtceu:small_golden_sheen_sapphire_dust", "gtceu:small_gold_dust")
    //shrineReward("whiteveil", 2, "gtceu:quartzite_gem", "gtceu:small_amethyst_dust", null)
    shrineReward("amethystback", 5, "minecraft:amethyst_shard", "gtceu:magnesiotaaffeite_2n2s_gem", "gtceu:tiny_indium_dust")
    shrineReward("stonefish", 5, "minecraft:smooth_stone", "gtceu:nickel_dust", "gtceu:tiny_thulium_dust")
    shrineReward("fossilized_angelfish", 4, "minecraft:bone", "architects_palette:withered_bone", "tconstruct:necrotic_bone")
    shrineReward("dripfin", 1, "minecraft:dripstone_block", "minecraft:small_dripleaf", null)
    shrineReward("yellowstone_fish", 2, "minecraft:pointed_dripstone", "gtceu:small_sulfur_dust", null)
    shrineReward("lush_pike", 6, "minecraft:moss_block", "gtceu:moss_opal_gem", "gtceu:uranium_235_dust")
    shrineReward("vivid_moss", 1, "minecraft:moss_carpet", "gtceu:plant_ball", null)
    shrineReward("the_quarrish", 3, "minecraft:spore_blossom", "gtceu:clay_dust", "gtceu:sphalerite_dust")
    //shrineReward("ghostly_pike", 2, "gtceu:quartzite_gem", "gtceu:small_amethyst_dust", null)
    shrineReward("aquamarine_pike", 4, "gtceu:beryl_gem", "gtceu:aquamarine_gem", "gtceu:small_potassium_dust")
    shrineReward("garnet_mackerel", 3, "gtceu:almandine_gem", "gtceu:pyrope_gem", "gtceu:spessartine_gem")
    shrineReward("bright_amethyst_snapper", 5, "minecraft:amethyst_block", "tconstruct:amethyst_bronze_ingot", "minecraft:budding_amethyst")
    shrineReward("dark_amethyst_snapper", 5, "minecraft:amethyst_block", "tconstruct:hepatizon_ingot", "minecraft:budding_amethyst")
    shrineReward("deepslatefish", 2, "minecraft:deepslate", "gtceu:small_redstone_dust", null)
    shrineReward("sculkfish", 3, "minecraft:sculk", "gtceu:small_diamond_dust", null)
    shrineReward("ward", 6, "minecraft:sculk_catalyst", "gtceu:sculk_dust", "gtceu:neptunium_dust")
    //shrineReward("glowing_dark", 5, "minecraft:deepslate", "gtceu:small_redstone_dust", null)
    //shrineReward("suneater", 5, "minecraft:deepslate", "gtceu:small_redstone_dust", null)
    //shrineReward("pyrotrout", 5, "minecraft:deepslate", "gtceu:small_redstone_dust", null)
    //shrineReward("embergill", 5, "minecraft:deepslate", "gtceu:small_redstone_dust", null)
    //shrineReward("scalding_pike", 5, "minecraft:deepslate", "gtceu:small_redstone_dust", null)
    //shrineReward("magma_fish", 5, "minecraft:deepslate", "gtceu:small_redstone_dust", null)
    shrineReward("glowstone_seeker", 3, "minecraft:glowstone_dust", "gtceu:small_magnesium_dust", null)
    shrineReward("glowstone_pufferfish", 4, "minecraft:glowstone", "gtceu:small_cerium_dust", null)
    //shrineReward("willish", 3, "minecraft:glowstone_dust", "gtceu:small_magnesium_dust", null)
    //shrineReward("cerberay", 3, "minecraft:glowstone_dust", "gtceu:small_magnesium_dust", null)
    //shrineReward("charfish", 3, "minecraft:glowstone_dust", "gtceu:small_magnesium_dust", null)
    shrineReward("end_glow", 2, "minecraft:end_stone", "gtceu:small_ender_pearl_dust", null)
    shrineReward("voidbiter", 6, "gtceu:ender_eye_dust", "gtceu:platinum_dust", "gtceu:quantum_eye")
    // TODO
    
})