ServerEvents.recipes(event => {
    // Manually remove bad autogenerated block casting recipes (TODO: more will show up as we define more ore byproducts in ore_modification.js)
    // Tin
    // Silver
    event.remove({id: "gm_construct:smeltery/casting/metal/iodargyrite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/pyrargyrite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/xanthoconite/block"})
    // Lead
    event.remove({id: "gm_construct:smeltery/casting/metal/minium/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/molybdomenite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/seeligerite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/phosgenite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/anglesite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/pyromorphite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/vanadinite/block"})
    // Zinc
    event.remove({id: "gm_construct:smeltery/casting/metal/leiteite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/sweetite/block"})
    // Thorium
    event.remove({id: "gm_construct:smeltery/casting/metal/thorianite/block"})
    // Manganese
    event.remove({id: "gm_construct:smeltery/casting/metal/bixbyite_mn/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/chambersite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/rhodochrosite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/allactite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/retzian_ce/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/retzian_la/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/vayrynenite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/braunite/block"})
    // Uranium
    // Platinum
    // Bismuth
    event.remove({id: "gm_construct:smeltery/casting/metal/bismutite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/dreyerite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/eulytine/block"})
    // Copper
    event.remove({id: "gm_construct:smeltery/casting/metal/belloite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/cuprite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/cuprostibite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/malachite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/marshite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/balyakinite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/chalcomenite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/jensenite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/rajite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/azurite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/azurmalachite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/langite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/cesiodymite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/clinoclase/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/cornwallite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/chalcophyllite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/euchroite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/dioptase/block"})
    // Gold
    // Nickel
    // Electrum
    // Antimony
    // Indium
    // Soldering Alloy
    // Brass
    // Tantalum
    // Bronze
    // Iron
    event.remove({id: "gm_construct:smeltery/casting/metal/siderite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/butlerite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/romerite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/triphylite/block"})
    event.remove({id: "gm_construct:smeltery/casting/metal/phosphosiderite/block"})
    // Cobalt
    event.remove({id: "gm_construct:smeltery/casting/metal/erythrite/block"})
    // Chromium
    
    // Allow use of constantan to make cupronickel parts. Can't do it with tags because of tcon's shenanigans using fake_ingot with NBT instead of an actual ingot item.
    const constantanIngot = Item.of('tconstruct:fake_ingot', 1, '{Material:"tconstruct:constantan"}').strongNBT()
    const constantanBlock = Item.of('tconstruct:fake_storage_block', 1, '{Material:"tconstruct:constantan"}').strongNBT()
    // Blocks/ingots/nuggets
    // Initial exception: allow crafting from cupronickel block to ingot and vice versa, since the block looks nice.
    event.shapeless(Item.of('tconstruct:fake_ingot', 9, '{Material:"tconstruct:constantan"}').strongNBT(), [constantanBlock])
    event.shapeless(constantanBlock, [constantanIngot, constantanIngot, constantanIngot, constantanIngot, constantanIngot, constantanIngot, constantanIngot, constantanIngot, constantanIngot])
    event.shapeless("9x gtceu:cupronickel_nugget", [constantanIngot])

    // Plate
    event.recipes.gtceu.bender("kubejs:tcon/constantan_to_cupronickel_plate_bender")
        .itemInputs(constantanIngot)
        .itemOutputs("gtceu:cupronickel_plate")
        .circuit(1)
        .duration(60)
        .EUt(24)
    event.recipes.gtceu.forge_hammer("kubejs:tcon/constantan_to_cupronickel_plate_forge_hammer")
        .itemInputs(Item.of('tconstruct:fake_ingot', 3, '{Material:"tconstruct:constantan"}').strongNBT())
        .itemOutputs("2x gtceu:cupronickel_plate")
        .duration(60)
        .EUt(16)
    event.recipes.gtceu.extruder("kubejs:tcon/constantan_to_cupronickel_plate_extruder")
        .itemInputs(constantanIngot)
        .itemOutputs("gtceu:cupronickel_plate")
        .notConsumable("gtceu:plate_extruder_mold")
        .duration(60)
        .EUt(56)
    event.recipes.gtceu.cutter("kubejs:tcon/constantan_to_cupronickel_plate_cutter")
        .itemInputs(constantanBlock)
        .itemOutputs("9x gtceu:cupronickel_plate")
        .duration(48*20)
        .EUt(30)
    event.shaped("1x gtceu:cupronickel_plate", [
        " H ",
        " I ",
        " I "
    ], {
        H: "#gtceu:tools/crafting_hammers",
        I: constantanIngot
    }).id("kubejs:tcon/constantan_to_cupronickel_plate_shaped")

    // Double Plate
    event.recipes.gtceu.bender("kubejs:tcon/constantan_to_cupronickel_double_plate_bender")
        .itemInputs(Item.of('tconstruct:fake_ingot', 2, '{Material:"tconstruct:constantan"}').strongNBT())
        .itemOutputs("gtceu:double_cupronickel_plate")
        .circuit(2)
        .duration(120)
        .EUt(96)

    // Foil
    event.recipes.gtceu.bender("kubejs:tcon/constantan_to_cupronickel_foil_bender")
        .itemInputs(constantanIngot)
        .itemOutputs("4x gtceu:cupronickel_foil")
        .circuit(10)
        .duration(60)
        .EUt(24)

    // Dust
    event.recipes.gtceu.macerator("kubejs:tcon/constantan_to_cupronickel_dust_macerator")
        .itemInputs(constantanIngot)
        .itemOutputs("gtceu:cupronickel_dust")
        .duration(60)
        .EUt(2)

    // Rod
    event.recipes.gtceu.lathe("kubejs:tcon/constantan_to_cupronickel_rod_lathe")
        .itemInputs(constantanIngot)
        .itemOutputs("2x gtceu:cupronickel_rod")
        .duration(120)
        .EUt(16)
    event.recipes.gtceu.extruder("kubejs:tcon/constantan_to_cupronickel_rod_extruder")
        .itemInputs(constantanIngot)
        .itemOutputs("2x gtceu:cupronickel_rod")
        .notConsumable("gtceu:rod_extruder_mold")
        .duration(120)
        .EUt(42)
    event.shaped("gtceu:cupronickel_rod", [
        "F  ",
        " I ",
        "   "
    ], {
        F: "#gtceu:tools/crafting_files",
        I: constantanIngot
    }).id("kubejs:tcon/constantan_to_cupronickel_rod_shaped")

    // Fine Wire
    event.recipes.gtceu.wiremill("kubejs:tcon/constantan_to_cupronickel_fine_wire_wiremill")
        .itemInputs(constantanIngot)
        .itemOutputs("8x gtceu:fine_cupronickel_wire")
        .circuit(3)
        .duration(180)
        .EUt(7)

    // Wires (various thicknesses)
    event.recipes.gtceu.wiremill("kubejs:tcon/constantan_to_cupronickel_1x_wire_wiremill")
        .itemInputs(constantanIngot)
        .itemOutputs("2x gtceu:cupronickel_single_wire")
        .circuit(1)
        .duration(60)
        .EUt(7)
    event.recipes.gtceu.wiremill("kubejs:tcon/constantan_to_cupronickel_2x_wire_wiremill")
        .itemInputs(constantanIngot)
        .itemOutputs("gtceu:cupronickel_double_wire")
        .circuit(2)
        .duration(60)
        .EUt(14)
    event.recipes.gtceu.wiremill("kubejs:tcon/constantan_to_cupronickel_4x_wire_wiremill")
        .itemInputs(Item.of('tconstruct:fake_ingot', 2, '{Material:"tconstruct:constantan"}').strongNBT())
        .itemOutputs("gtceu:cupronickel_quadruple_wire")
        .circuit(4)
        .duration(120)
        .EUt(7)
    event.recipes.gtceu.wiremill("kubejs:tcon/constantan_to_cupronickel_8x_wire_wiremill")
        .itemInputs(Item.of('tconstruct:fake_ingot', 4, '{Material:"tconstruct:constantan"}').strongNBT())
        .itemOutputs("gtceu:cupronickel_octal_wire")
        .circuit(8)
        .duration(240)
        .EUt(7)
    event.recipes.gtceu.wiremill("kubejs:tcon/constantan_to_cupronickel_16x_wire_wiremill")
        .itemInputs(Item.of('tconstruct:fake_ingot', 8, '{Material:"tconstruct:constantan"}').strongNBT())
        .itemOutputs("gtceu:cupronickel_hex_wire")
        .circuit(16)
        .duration(480)
        .EUt(7)
})