ServerEvents.recipes(event => {
    // Tungsten processing hardmode changes
    event.remove({ id: "gtceu:electrolyzer/tungstic_acid_electrolysis" })

    event.recipes.gtceu.extractor("kubejs:tungsten_trioxide_dust")
        .itemInputs("7x #forge:dusts/tungstic_acid")
        .itemOutputs("4x gtceu:tungsten_trioxide_dust")
        .outputFluids(Fluid.of("minecraft:water", 1000))
        .duration(160).EUt(16)

    event.recipes.gtceu.electric_blast_furnace("kubejs:hot_tungsten_ingot")
        .itemInputs("8x #forge:dusts/tungsten_trioxide", "3x #forge:dusts/carbon")
        .itemOutputs("2x gtceu:hot_tungsten_ingot")
        .outputFluids(Fluid.of("gtceu:carbon_dioxide", 3000))
        .blastFurnaceTemp(3600)
        .duration(2400).EUt(1920)

    event.recipes.gtceu.chemical_reactor("kubejs:tungsten_dust")
        .itemInputs("4x #forge:dusts/tungsten_trioxide")
        .inputFluids(Fluid.of("gtceu:hydrogen", 6000))
        .itemOutputs("gtceu:tungsten_dust")
        .outputFluids(Fluid.of("water", 3000))
        .duration(210).EUt(960)

    // Tungsten line ores
    // Hubnerite (6 MnWO4 + 2 HCl -> 7 H2WO4 + 3 MnCl2)
    event.recipes.gtceu.chemical_bath("kubejs:tungstenline/hubnerite")
        .itemInputs("6x gtceu:hubnerite_dust")
        .inputFluids("gtceu:hydrochloric_acid 2000")
        .itemOutputs("7x gtceu:tungstic_acid_dust", "3x gtceu:manganese_chloride_dust")
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(210)
    // Ferberite (6 FeWO4 + 2 HCl -> 7 H2WO4 + 3 FeCl2)
    event.recipes.gtceu.chemical_bath("kubejs:tungstenline/ferberite")
        .itemInputs("6x gtceu:ferberite_dust")
        .inputFluids("gtceu:hydrochloric_acid 2000")
        .itemOutputs("7x gtceu:tungstic_acid_dust", "3x gtceu:iron_ii_chloride_dust")
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(210)
    // Krasnoselskite (6 CoWO4 + 2 HCl -> 7 H2WO4 + 3 CoCl2)
    event.recipes.gtceu.chemical_bath("kubejs:tungstenline/krasnoselskite")
        .itemInputs("6x gtceu:krasnoselskite_dust")
        .inputFluids("gtceu:hydrochloric_acid 2000")
        .itemOutputs("7x gtceu:tungstic_acid_dust", "3x gtceu:cobalt_chloride_dust")
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(210)
    // Stolzite (6 PbWO4 + 2 HCl -> 7 H2WO4 + 3 PbCl2)
    event.recipes.gtceu.chemical_bath("kubejs:tungstenline/stolzite")
        .itemInputs("6x gtceu:stolzite_dust")
        .inputFluids("gtceu:hydrochloric_acid 2000")
        .itemOutputs("7x gtceu:tungstic_acid_dust", "3x gtceu:lead_chloride_dust")
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(210)
    // Russellite (27 Bi2WO6 + 6 HCl -> 21 H2WO4 + 8 BiCl3 + 10 Bi2O3)
    event.recipes.gtceu.chemical_bath("kubejs:tungstenline/russellite")
        .itemInputs("27x gtceu:russellite_dust")
        .inputFluids("gtceu:hydrochloric_acid 6000")
        .itemOutputs("21x gtceu:tungstic_acid_dust", "8x gtceu:bismuth_chloride_dust", "10x gtceu:bismite_dust")
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(630)
    // Tungstite (5 WO3(H2O) + 1 HCl -> 4 WO3 + 2 (HCl)(H2O))
    event.recipes.gtceu.chemical_bath("kubejs:tungstenline/tungstite")
        .itemInputs("5x gtceu:tungstite_dust")
        .inputFluids("gtceu:hydrochloric_acid 1000")
        .itemOutputs("4x gtceu:tungsten_trioxide_dust")
        .outputFluids("gtceu:diluted_hydrochloric_acid 2000")
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(210)
    // Hydrotungstite (6 WO3(H2O)2 + 2 HCl -> 4 WO3 + 4 (HCl)(H2O))
    event.recipes.gtceu.chemical_bath("kubejs:tungstenline/hydrotungstite")
        .itemInputs("6x gtceu:hydrotungstite_dust")
        .inputFluids("gtceu:hydrochloric_acid 2000")
        .itemOutputs("4x gtceu:tungsten_trioxide_dust")
        .outputFluids("gtceu:diluted_hydrochloric_acid 4000")
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(210)
    // Yttrotungstite-(Ce) (15 CeW2O9H3 + 3 HCl -> 14 H2WO4 + 4 CeCl3 + H2O) -> Init CeCl3
    event.recipes.gtceu.chemical_bath("kubejs:tungstenline/yttrotungstite_ce")
        .itemInputs("15x gtceu:yttrotungstite_ce_dust")
        .inputFluids("gtceu:hydrochloric_acid 3000")
        .itemOutputs("14x gtceu:tungstic_acid_dust", "4x gtceu:cerium_trichloride_dust")
        .outputFluids("minecraft:water 1000")
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(420)
    // Yttrotungstite-(Y) (15 YW2O9H3 + 3 HCl -> 14 H2WO4 + 4 YCl3 + H2O) -> Init YCl3
    event.recipes.gtceu.chemical_bath("kubejs:tungstenline/yttrotungstite_y")
        .itemInputs("15x gtceu:yttrotungstite_y_dust")
        .inputFluids("gtceu:hydrochloric_acid 3000")
        .itemOutputs("14x gtceu:tungstic_acid_dust", "4x gtceu:yttrium_trichloride_dust")
        .outputFluids("minecraft:water 1000")
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(420)
    // Anthoinite (11 AlWO6H3 + 3 HCl -> 7 H2WO4 + 4 AlCl3 + H2O)
    event.recipes.gtceu.chemical_bath("kubejs:tungstenline/anthoinite")
        .itemInputs("11x gtceu:anthoinite_dust")
        .inputFluids("gtceu:hydrochloric_acid 3000")
        .itemOutputs("7x gtceu:tungstic_acid_dust", "4x gtceu:aluminium_chloride_dust")
        .outputFluids("minecraft:water 1000")
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(210)
    // Ootannite (27 Th2W4O16(H2O)5 + 5 HCl -> 28 H2WO4 + 10 (H2O)(HCl) + 2 Th)
    event.recipes.gtceu.chemical_bath("kubejs:tungstenline/ootannite")
        .itemInputs("27x gtceu:ootannite_dust")
        .inputFluids("gtceu:hydrochloric_acid 5000")
        .itemOutputs("28x gtceu:tungstic_acid_dust", "2x gtceu:thorium_dust")
        .outputFluids("gtceu:diluted_hydrochloric_acid 10000")
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(840)
    
    // Remaining tungsten dusts (more complex, need customized decomps)
    event.recipes.gtceu.electric_blast_furnace("kubejs:tungsten/tungstenite_blasting")
        .itemInputs("3x gtceu:tungstenite_dust")
        .inputFluids("gtceu:oxygen 4000")
        .itemOutputs("1x gtceu:hot_tungsten_ingot")
        .outputFluids("gtceu:sulfur_dioxide 2000")
        .blastFurnaceTemp(3600)
        .duration(2400).EUt(1920)
    event.recipes.gtceu.electric_blast_furnace("kubejs:tungsten/catamarcaite_blasting")
        .itemInputs("16x gtceu:catamarcaite_dust")
        .inputFluids("gtceu:oxygen 16000")
        .itemOutputs("12x minecraft:copper_ingot", "1x gtceu:tin_ingot", "1x gtceu:hot_tungsten_ingot")
        .outputFluids("gtceu:sulfur_dioxide 8000")
        .blastFurnaceTemp(3600)
        .duration(2400).EUt(1920)
    event.recipes.gtceu.ore_digestion("kubejs:tungsten/ophirite_digestion")
        .itemInputs("146x gtceu:ophirite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:hydrochloric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("4x gtceu:quicklime_dust", "8x gtceu:magnesia_dust", "4x gtceu:zincite_dust", "6x gtceu:pyrolusite_dust", "5x gtceu:hematite_dust", "126x gtceu:tungstic_acid_dust")
        .chancedFluidOutput("gtceu:diluted_hydrochloric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1200).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:tungsten/uranotungstite_digestion")
        .itemInputs("23x gtceu:uranotungstite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:hydrochloric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("6x gtceu:barite_dust", "2x gtceu:massicot_dust", "2x gtceu:uraninite_dust", "7x gtceu:tungstic_acid_dust", "5x gtceu:goethite_dust")
        .chancedFluidOutput("gtceu:diluted_hydrochloric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1200).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:tungsten/natrowalentaite_digestion")
        .itemInputs("29x gtceu:natrowalentaite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:hydrochloric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("7x gtceu:magnetite_dust", "4x gtceu:salt_dust", "5x gtceu:arsenic_trioxide_dust", "7x gtceu:tungstic_acid_dust", "2x gtceu:phosphate_dust")
        .chancedFluidOutput("gtceu:diluted_hydrochloric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1200).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:tungsten/johnsenite_ce_digestion")
        .itemInputs("136x gtceu:johnsenite_ce_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:hydrochloric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("6x gtceu:sodium_bicarbonate_dust", "22x gtceu:salt_dust", "6x gtceu:ceria_dust", "9x gtceu:pyrolusite_dust", "9x gtceu:zirconia_dust",
            "75x gtceu:silicon_dioxide_dust", "7x gtceu:tungstic_acid_dust")
        .chancedFluidOutput("gtceu:diluted_hydrochloric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1200).EUt(GTValues.VHA[GTValues.IV])

    // Indium line combinations
    var indiOres = Array.from(new Set([
        "galena", "sphalerite", "alburnite", "xuwenyuanite", "acanthite", "spryite", "argentite", "aguilarite", "cervelleite", "fischesserite", "sopcheite", "ruizhongite",
        "laforetite", "empressite", "sylvanite", "pyrargyrite", "xanthoconite", "samsonite", "laffittite", "stephanite", "quadratite", "manganoquadratite", "interliveingite",
        "rathite", "veenite", "sartorite", "heptasartorite", "polloneite", "boulangerite", "buynite", "cylindrite", "oscarkempffite", "diaphorite", "jordanite", "geocronite",
        "stilleite"
    ]))
    const seenIndiumPairs = new Set()
    indiOres.forEach((ore1, index) => {
        indiOres.forEach((ore2, i) => {
            const pairKey = [ore1, ore2].sort().join("_")
            if (!(pairKey === "galena_sphalerite" || seenIndiumPairs.has(pairKey) || ore1 === ore2)) {
                seenIndiumPairs.add(pairKey)
                event.recipes.gtceu.mixer(`kubejs:indiumline/${ore1}_${ore2}`)
                    .itemInputs(`gtceu:purified_${ore1}_ore`, `gtceu:purified_${ore2}_ore`)
                    .inputFluids("gtceu:sulfuric_acid 4000")
                    .outputFluids("gtceu:indium_concentrate 1000")
                    .EUt(150)
                    .duration(60)
            }
        })
    })

    // Titanium line
    // Brookite/Anatase into TiCl4 (same as rutile)
    event.recipes.gtceu.chemical_reactor("kubejs:titanium/brookite_to_ticl4")
        .itemInputs("2x gtceu:carbon_dust", "1x gtceu:brookite_dust", )
        .inputFluids("gtceu:chlorine 4000")
        .outputFluids("gtceu:carbon_monoxide 2000", "gtceu:titanium_tetrachloride 1000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(400)
    event.recipes.gtceu.chemical_reactor("kubejs:titanium/anatase_to_ticl4")
        .itemInputs("2x gtceu:carbon_dust", "1x gtceu:anatase_dust", )
        .inputFluids("gtceu:chlorine 4000")
        .outputFluids("gtceu:carbon_monoxide 2000", "gtceu:titanium_tetrachloride 1000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(400)

    // Simple titanium ores (similar to ilmenite) 
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/wangxibinite_decompose")
        .itemInputs("2x gtceu:wangxibinite_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("gtceu:wrought_iron_ingot", "3x gtceu:rutile_dust")
        .duration(800).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/toledoite_decompose")
        .itemInputs("3x gtceu:toledoite_dust")
        .inputFluids("gtceu:oxygen 4000")
        .itemOutputs("gtceu:wrought_iron_ingot", "3x gtceu:rutile_dust", "3x gtceu:silicon_dioxide_dust")
        .duration(800).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/florenskyite_decompose")
        .itemInputs("3x gtceu:florenskyite_dust")
        .inputFluids("gtceu:oxygen 4000")
        .itemOutputs("gtceu:wrought_iron_ingot", "3x gtceu:rutile_dust", "5x gtceu:phosphate_dust")
        .duration(800).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/hongquiite_decompose")
        .itemInputs("2x gtceu:hongquiite_dust")
        .inputFluids("gtceu:oxygen 1000")
        .itemOutputs("3x gtceu:rutile_dust")
        .duration(800).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/magneliite_decompose")
        .itemInputs("11x gtceu:magneliite_dust")
        .inputFluids("gtceu:oxygen 1000")
        .itemOutputs("12x gtceu:rutile_dust")
        .duration(800).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/ulvospinel_decompose")
        .itemInputs("7x gtceu:ulvospinel_dust", "gtceu:carbon_dust")
        .itemOutputs("2x gtceu:wrought_iron_ingot", "3x gtceu:rutile_dust")
        .outputFluids("gtceu:carbon_dioxide 1000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/griffinite_decompose")
        .itemInputs("8x gtceu:griffinite_dust", "3x gtceu:carbon_dust")
        .itemOutputs("2x gtceu:aluminium_ingot", "3x gtceu:rutile_dust")
        .outputFluids("gtceu:carbon_monoxide 3000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/heamanite_ce_decompose")
        .itemInputs("20x gtceu:heamanite_ce_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("12x gtceu:rutile_dust", "6x gtceu:potash_dust", "6x gtceu:ceria_dust")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/perovskite_decompose")
        .itemInputs("5x gtceu:perovskite_dust", "gtceu:carbon_dust")
        .itemOutputs("1x gtceu:quicklime_dust", "3x gtceu:rutile_dust")
        .outputFluids("gtceu:carbon_monoxide 1000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/macedonite_decompose")
        .itemInputs("5x gtceu:macedonite_dust", "gtceu:carbon_dust")
        .itemOutputs("1x gtceu:lead_ingot", "3x gtceu:rutile_dust")
        .outputFluids("gtceu:carbon_dioxide 1000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/loparite_decompose")
        .itemInputs("10x gtceu:loparite_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 1000")
        .itemOutputs("1x gtceu:rare_earth_dust", "6x gtceu:rutile_dust", "6x gtceu:soda_ash_dust")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/tantalaeschynite_ce_decompose")
        .itemInputs("16x gtceu:tantalaeschynite_ce_dust", "gtceu:carbon_dust")
        .itemOutputs("3x gtceu:ceria_dust", "3x gtceu:rutile_dust", "4x gtceu:tantalum_pentoxide_dust") // Not fully accurate on the oxygen or tantalum ratios, but I don't want to have to introduce another tantalum oxide just for this.
        .outputFluids("gtceu:carbon_dioxide 1000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/aeschynite_nd_decompose")
        .itemInputs("18x gtceu:aeschynite_nd_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("5x gtceu:neodymia_dust", "6x gtceu:rutile_dust", "7x gtceu:niobium_pentoxide_dust")
        .outputFluids("gtceu:carbon_dioxide 1000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/aeschynite_ce_decompose")
        .itemInputs("18x gtceu:aeschynite_ce_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("5x gtceu:cerium_trioxide_dust", "6x gtceu:rutile_dust", "7x gtceu:niobium_pentoxide_dust")
        .outputFluids("gtceu:carbon_dioxide 1000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/aeschynite_y_decompose")
        .itemInputs("18x gtceu:aeschynite_y_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("5x gtceu:yttria_dust", "6x gtceu:rutile_dust", "7x gtceu:niobium_pentoxide_dust")
        .outputFluids("gtceu:carbon_dioxide 1000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/tivanite_decompose")
        .itemInputs("14x gtceu:tivanite_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("7x gtceu:vanadium_pentoxide_dust", "6x gtceu:rutile_dust")
        .outputFluids("gtceu:steam 9600")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/brannerite_decompose")
        .itemInputs("9x gtceu:brannerite_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("3x gtceu:uraninite_dust", "6x gtceu:rutile_dust")
        .outputFluids("gtceu:carbon_dioxide 1000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/zirconolite_decompose")
        .itemInputs("11x gtceu:zirconolite_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("2x gtceu:quicklime_dust", "3x gtceu:zirconia_dust", "6x gtceu:rutile_dust")
        .outputFluids("gtceu:carbon_dioxide 1000")
        .duration(3200).EUt(GTValues.VA[GTValues.EV]).blastFurnaceTemp(2400)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/carmeltazite_decompose")
        .itemInputs("11x gtceu:carmeltazite_dust")
        .inputFluids("gtceu:oxygen 6000")
        .itemOutputs("3x gtceu:zirconia_dust", "2x gtceu:aluminium_ingot", "12x gtceu:rutile_dust")
        .duration(3200).EUt(GTValues.VA[GTValues.EV]).blastFurnaceTemp(2400)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/mannardite_decompose")
        .itemInputs("25x gtceu:mannardite_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("1x gtceu:barium_dust", "18x gtceu:rutile_dust", "7x gtceu:vanadium_pentoxide_dust")
        .outputFluids("gtceu:carbon_monoxide 1000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/priderite_decompose")
        .itemInputs("50x gtceu:priderite_dust", "gtceu:carbon_dust")
        .itemOutputs("3x gtceu:potash_dust", "42x gtceu:rutile_dust", "7x gtceu:vanadium_pentoxide_dust", "2x gtceu:wrought_iron_ingot")
        .outputFluids("gtceu:carbon_dioxide 1000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/sabinaite_decompose")
        .itemInputs("33x gtceu:sabinaite_dust")
        .inputFluids("gtceu:oxygen 4000")
        .itemOutputs("12x gtceu:soda_ash_dust", "6x gtceu:zirconia_dust", "3x gtceu:rutile_dust")
        .outputFluids("gtceu:carbon_dioxide 2000")
        .duration(3200).EUt(GTValues.VA[GTValues.EV]).blastFurnaceTemp(2400)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/zircosulfate_decompose")
        .itemInputs("14x gtceu:zircosulfate_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("3x gtceu:zirconia_dust", "3x gtceu:rutile_dust")
        .outputFluids("gtceu:sulfuric_acid 4000")
        .duration(3200).EUt(GTValues.VA[GTValues.EV]).blastFurnaceTemp(2400)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/calamaite_decompose")
        .itemInputs("8x gtceu:calamaite_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("6x gtceu:sodium_bicarbonate_dust", "3x gtceu:rutile_dust")
        .outputFluids("gtceu:sulfuric_acid 2000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/hochleitnerite_decompose")
        .itemInputs("35x gtceu:hochleitnerite_dust")
        .itemOutputs("2x gtceu:manganese_ingot", "9x gtceu:rutile_dust", "56x gtceu:phosphorus_pentoxide_dust")
        .outputFluids("gtceu:steam 153600")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/rubinite_decompose")
        .itemInputs("20x gtceu:rubinite_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("6x gtceu:quicklime_dust", "6x gtceu:rutile_dust", "9x gtceu:silicon_dioxide_dust")
        .outputFluids("gtceu:carbon_monoxide 1000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/titanite_decompose")
        .itemInputs("8x gtceu:titanite_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("5x gtceu:calcite_dust", "3x gtceu:rutile_dust", "3x gtceu:silicon_dioxide_dust")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/matsubaraite_decompose")
        .itemInputs("35x gtceu:matsubaraite_dust", "2x gtceu:carbon_dust")
        .itemOutputs("4x gtceu:strontium_dust", "15x gtceu:rutile_dust", "12x gtceu:silicon_dioxide_dust")
        .outputFluids("gtceu:carbon_dioxide 2000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/benitoite_decompose")
        .itemInputs("14x gtceu:benitoite_dust", "gtceu:carbon_dust")
        .itemOutputs("1x gtceu:barium_dust", "3x gtceu:rutile_dust", "9x gtceu:silicon_dioxide_dust")
        .outputFluids("gtceu:carbon_monoxide 1000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/korobitsynite_decompose")
        .itemInputs("25x gtceu:korobitsynite_dust", "3x gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 6000")
        .itemOutputs("18x gtceu:sodium_bicarbonate_dust", "6x gtceu:rutile_dust", "12x gtceu:silicon_dioxide_dust")
        .outputFluids("gtceu:steam 28800")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/kosnarite_decompose")
        .itemInputs("12x gtceu:kosnarite_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 46000")
        .itemOutputs("3x gtceu:potash_dust", "12x gtceu:zirconia_dust", "84x gtceu:phosphorus_pentoxide_dust")
        .outputFluids("gtceu:carbon_monoxide 1000")
        .duration(3200).EUt(GTValues.VA[GTValues.EV]).blastFurnaceTemp(2400)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/zircon_decompose")
        .itemInputs("6x gtceu:zircon_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("3x gtceu:zirconia_dust", "3x gtceu:silicon_dioxide_dust")
        .outputFluids("gtceu:carbon_dioxide 1000")
        .duration(3200).EUt(GTValues.VA[GTValues.EV]).blastFurnaceTemp(2400)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/hafnon_decompose")
        .itemInputs("6x gtceu:hafnon_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("3x gtceu:hafnia_dust", "3x gtceu:silicon_dioxide_dust")
        .outputFluids("gtceu:carbon_dioxide 1000")
        .duration(3200).EUt(GTValues.VA[GTValues.LuV]).blastFurnaceTemp(4000)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/gittinsite_decompose")
        .itemInputs("11x gtceu:gittinsite_dust", "gtceu:carbon_dust")
        .itemOutputs("5x gtceu:calcite_dust", "3x gtceu:zirconia_dust", "6x gtceu:silicon_dioxide_dust")
        .duration(3200).EUt(GTValues.VA[GTValues.EV]).blastFurnaceTemp(2400)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/bazirite_decompose")
        .itemInputs("14x gtceu:bazirite_dust", "gtceu:carbon_dust")
        .itemOutputs("1x gtceu:barium_dust", "3x gtceu:zirconia_dust", "9x gtceu:silicon_dioxide_dust")
        .outputFluids("gtceu:carbon_monoxide 1000")
        .duration(3200).EUt(GTValues.VA[GTValues.EV]).blastFurnaceTemp(2400)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/armstrongite_decompose")
        .itemInputs("26x gtceu:armstrongite_dust", "gtceu:carbon_dust")
        .itemOutputs("5x gtceu:calcite_dust", "3x gtceu:zirconia_dust", "18x gtceu:silicon_dioxide_dust")
        .outputFluids("gtceu:steam 28800")
        .duration(3200).EUt(GTValues.VA[GTValues.EV]).blastFurnaceTemp(2400)

    // Remaining (complex) titanium ores
    event.recipes.gtceu.ore_digestion("kubejs:titanium/botuobinskite_digestion")
        .itemInputs("62x gtceu:botuobinskite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("1x gtceu:strontium_dust", "5x gtceu:hematite_dust", "4x gtceu:magnesia_dust", "24x gtceu:chromium_trioxide_dust", "36x gtceu:titanium_dioxide_mix_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/lakargiite_digestion")
        .itemInputs("20x gtceu:lakargiite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("8x gtceu:quicklime_dust", "6x gtceu:zirconia_dust", "3x gtceu:cassiterite_dust", "3x gtceu:titanium_dioxide_mix_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/panguite_digestion")
        .itemInputs("30x gtceu:panguite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("9x gtceu:titanium_dioxide_mix_dust", "8x gtceu:corundum_dust", "5x gtceu:scandia_dust", "4x gtceu:magnesia_dust", "3x gtceu:zirconia_dust", "2x gtceu:quicklime_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/lindsleyite_digestion")
        .itemInputs("120x gtceu:lindsleyite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("1x gtceu:barium_dust", "1x gtceu:strontium_dust", "3x gtceu:zirconia_dust", "2x gtceu:quicklime_dust", "20x gtceu:hematite_dust", "7x gtceu:magnetite_dust", 
            "2x gtceu:magnesia_dust", "48x gtceu:titanium_dioxide_mix_dust", "48x gtceu:chromium_trioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/loveringite_digestion")
        .itemInputs("240x gtceu:loveringite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("4x gtceu:quicklime_dust", "3x gtceu:ceria_dust", "3x gtceu:lanthana_dust", "65x gtceu:hematite_dust", "10x gtceu:magnesia_dust",
            "90x gtceu:titanium_dioxide_mix_dust", "48x gtceu:chromium_trioxide_dust", "20x gtceu:corundum_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/davidite_la_digestion")
        .itemInputs("144x gtceu:davidite_la_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("5x gtceu:lanthana_dust", "3x gtceu:yttria_dust", "3x gtceu:uraninite_dust", "35x gtceu:hematite_dust", "36x gtceu:titanium_dioxide_mix_dust",
            "32x gtceu:chromium_trioxide_dust", "21x gtceu:vanadium_pentoxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .outputFluids("gtceu:hydrofluoric_acid 12000")
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/davidite_ce_digestion")
        .itemInputs("144x gtceu:davidite_ce_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("6x gtceu:ceria_dust", "3x gtceu:yttria_dust", "3x gtceu:uraninite_dust", "35x gtceu:hematite_dust", "36x gtceu:titanium_dioxide_mix_dust",
            "32x gtceu:chromium_trioxide_dust", "21x gtceu:vanadium_pentoxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .outputFluids("gtceu:hydrofluoric_acid 12000")
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/davidite_y_digestion")
        .itemInputs("359x gtceu:davidite_y_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("5x gtceu:lanthana_dust", "3x gtceu:ceria_dust", "4x gtceu:sodium_peroxide_dust", "1x gtceu:quicklime_dust",
            "2x gtceu:massicot_dust", "8x gtceu:yttria_dust", "80x gtceu:hematite_dust", "12x gtceu:pyrolusite_dust", "174x gtceu:titanium_dioxide_mix_dust", 
            "63x gtceu:niobium_pentoxide_dust", "30x gtceu:zirconia_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/kangite_digestion")
        .itemInputs("40x gtceu:kangite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("13x gtceu:scandia_dust", "9x gtceu:titanium_dioxide_mix_dust", "8x gtceu:corundum_dust", "6x gtceu:zirconia_dust", "4x gtceu:magnesia_dust",
            "2x gtceu:quicklime_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/uranopolycrase_digestion")
        .itemInputs("18x gtceu:uranopolycrase_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("3x gtceu:uraninite_dust", "3x gtceu:yttria_dust", "9x gtceu:titanium_dioxide_mix_dust", "4x gtceu:niobium_pentoxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/euxenite_y_digestion")
        .itemInputs("54x gtceu:euxenite_y_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("5x gtceu:yttria_dust", "2x gtceu:quicklime_dust", "3x gtceu:ceria_dust", "3x gtceu:uraninite_dust", "1x gtceu:thorium_dust", 
            "25x gtceu:niobium_pentoxide_dust", "11x gtceu:tantalum_pentoxide_dust", "6x gtceu:titanium_dioxide_mix_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/thorutite_digestion")
        .itemInputs("46x gtceu:thorutite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("2x gtceu:thorium_dust", "3x gtceu:uraninite_dust", "2x gtceu:quicklime_dust", "24x gtceu:titanium_dioxide_mix_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/stefanweissite_digestion")
        .itemInputs("44x gtceu:stefanweissite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("9x gtceu:ceria_dust", "12x gtceu:zirconia_dust", "7x gtceu:niobium_pentoxide_dust", "12x gtceu:titanium_dioxide_mix_dust",
            "5x gtceu:hematite_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .outputFluids("gtceu:ree_sulfate_sludge 500")
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/laachite_digestion")
        .itemInputs("22x gtceu:laachite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("2x gtceu:quicklime_dust", "3x gtceu:pyrolusite_dust", "6x gtceu:zirconia_dust", "7x gtceu:niobium_pentoxide_dust",
            "3x gtceu:titanium_dioxide_mix_dust", "3x gtceu:hematite_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/tazzoliite_digestion")
        .itemInputs("36x gtceu:tazzoliite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("18x gtceu:barite_dust", "3x gtceu:sodium_hydroxide_dust", "6x gtceu:titanium_dioxide_mix_dust", "11x gtceu:niobium_pentoxide_dust",
            "3x gtceu:silicon_dioxide_dust", "5x gtceu:phosphate_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/asbecasite_digestion")
        .itemInputs("80x gtceu:asbecasite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("12x gtceu:quicklime_dust", "3x gtceu:titanium_dioxide_mix_dust", "3x gtceu:cassiterite_dust", "8x gtceu:beryllium_oxide_dust",
            "30x gtceu:arsenic_trioxide_dust", "12x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/bianchiniite_digestion")
        .itemInputs("20x gtceu:bianchiniite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("12x gtceu:barite_dust", "3x gtceu:titanium_dioxide_mix_dust", "5x gtceu:vanadate_dust", "10x gtceu:arsenic_trioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .outputFluids("gtceu:hydrofluoric_acid 1000")
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/azoproite_digestion")
        .itemInputs("36x gtceu:azoproite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("12x gtceu:magnesia_dust", "5x gtceu:hematite_dust", "7x gtceu:magnetite_dust", "3x gtceu:titanium_dioxide_mix_dust", "16x gtceu:borate_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/lehmannite_digestion")
        .itemInputs("85x gtceu:lehmannite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("10x gtceu:salt_dust", "2x gtceu:villiaumite_dust", "18x gtceu:sodium_hydroxide_dust", "24x gtceu:cupric_oxide_dust", "3x gtceu:titanium_dioxide_mix_dust",
            "20x gtceu:arsenic_trioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/sperlingite_digestion")
        .itemInputs("29x gtceu:sperlingite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("3x gtceu:potassium_hydroxide_dust", "3x gtceu:pyrolusite_dust", "4x gtceu:yellow_limonite_dust", "5x gtceu:corundum_dust",
            "3x gtceu:titanium_dioxide_mix_dust", "4x gtceu:phosphate_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .outputFluids("minecraft:water 14000")
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/tranquillityite_digestion")
        .itemInputs("40x gtceu:tranquillityite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("7x gtceu:magnetite_dust", "5x gtceu:hematite_dust", "6x gtceu:quicklime_dust", "3x gtceu:zirconia_dust", "9x gtceu:titanium_dioxide_mix_dust",
            "9x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/bortolanite_digestion")
        .itemInputs("30x gtceu:bortolanite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("3x gtceu:fluorite_dust", "6x gtceu:quicklime_dust", "3x gtceu:zirconia_dust", "2x gtceu:villiaumite_dust", "3x gtceu:sodium_hydroxide_dust",
            "3x gtceu:titanium_dioxide_mix_dust", "12x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/roumaite_digestion")
        .itemInputs("57x gtceu:roumaite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("3x gtceu:fluorite_dust", "12x gtceu:quicklime_dust", "8x gtceu:villiaumite_dust", "4x gtceu:niobium_pentoxide_dust",
            "3x gtceu:titanium_dioxide_mix_dust", "24x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .outputFluids("gtceu:ree_sulfate_sludge 1000")
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/kochite_digestion")
        .itemInputs("30x gtceu:kochite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("6x gtceu:villiaumite_dust", "4x gtceu:quicklime_dust", "3x gtceu:pyrolusite_dust", "3x gtceu:zirconia_dust",
            "3x gtceu:titanium_dioxide_mix_dust", "12x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/saamite_digestion")
        .itemInputs("33x gtceu:saamite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("6x gtceu:barite_dust", "2x gtceu:villiaumite_dust", "6x gtceu:sodium_hydroxide_dust", "6x gtceu:titanium_dioxide_mix_dust",
            "4x gtceu:niobium_pentoxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/epistolite_digestion")
        .itemInputs("35x gtceu:epistolite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("12x gtceu:sodium_hydroxide_dust", "7x gtceu:niobium_pentoxide_dust", "3x gtceu:titanium_dioxide_mix_dust",
            "12x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/innelite_digestion")
        .itemInputs("68x gtceu:innelite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("48x gtceu:barite_dust", "18x gtceu:titanium_dioxide_mix_dust", "9x gtceu:sodium_hydroxide_dust", "7x gtceu:sodium_bisulfate_dust",
            "6x gtceu:pyrolusite_dust", "5x gtceu:phosphate_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/polyphite_digestion")
        .itemInputs("29x gtceu:polyphite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("4x gtceu:villiaumite_dust", "21x gtceu:sodium_hydroxide_dust", "6x gtceu:titanium_dioxide_mix_dust", "6x gtceu:silicon_dioxide_dust",
            "15x gtceu:phosphate_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/bussenite_digestion")
        .itemInputs("26x gtceu:bussenite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("6x gtceu:sodium_bicarbonate_dust", "2x gtceu:villiaumite_dust", "12x gtceu:barite_dust", "4x gtceu:yellow_limonite_dust", "3x gtceu:titanium_dioxide_mix_dust",
            "6x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/hezuolinite_digestion")
        .itemInputs("35x gtceu:hezuolinite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("3x gtceu:strontium_dust", "3x gtceu:zirconia_dust", "9x gtceu:titanium_dioxide_mix_dust", "3x gtceu:hematite_dust", "12x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .outputFluids("gtceu:ree_sulfate_sludge 500")
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/orthojoaquinite_la_digestion")
        .itemInputs("45x gtceu:orthojoaquinite_la_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("3x gtceu:sodium_hydroxide_dust", "12x gtceu:barite_dust", "5x gtceu:lanthana_dust", "4x gtceu:yellow_limonite_dust", "6x gtceu:titanium_dioxide_mix_dust",
            "24x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/orthojoaquinite_ce_digestion")
        .itemInputs("45x gtceu:orthojoaquinite_ce_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("3x gtceu:sodium_hydroxide_dust", "12x gtceu:barite_dust", "6x gtceu:ceria_dust", "4x gtceu:yellow_limonite_dust", "6x gtceu:titanium_dioxide_mix_dust",
            "24x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/joaquinite_ce_digestion")
        .itemInputs("44x gtceu:joaquinite_ce_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("2x gtceu:villiaumite_dust", "12x gtceu:barite_dust", "6x gtceu:ceria_dust", "3x gtceu:hematite_dust", "6x gtceu:titanium_dioxide_mix_dust",
            "24x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/strontiojoaquinite_digestion")
        .itemInputs("46x gtceu:strontiojoaquinite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("2x gtceu:strontium_dust", "12x gtceu:barite_dust", "3x gtceu:sodium_hydroxide_dust", "4x gtceu:yellow_limonite_dust", "6x gtceu:titanium_dioxide_mix_dust",
            "24x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/lovozerite_digestion")
        .itemInputs("66x gtceu:lovozerite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("12x gtceu:sodium_hydroxide_dust", "4x gtceu:quicklime_dust", "3x gtceu:zirconia_dust", "3x gtceu:titanium_dioxide_mix_dust", "36x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/labyrinthite_digestion")
        .itemInputs("267x gtceu:labyrinthite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("6x gtceu:salt_dust", "42x gtceu:sodium_hydroxide_dust", "15x gtceu:potash_dust", "8x gtceu:strontium_dust", "24x gtceu:quicklime_dust",
            "7x gtceu:magnetite_dust", "18x gtceu:zirconia_dust", "3x gtceu:titanium_dioxide_mix_dust", "153x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/dualite_digestion")
        .itemInputs("263x gtceu:dualite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("4x gtceu:salt_dust", "102x gtceu:sodium_hydroxide_dust", "14x gtceu:quicklime_dust", "3x gtceu:ceria_dust", "1x gtceu:strontium_dust",
            "6x gtceu:pyrolusite_dust", "4x gtceu:yellow_limonite_dust", "12x gtceu:titanium_dioxide_mix_dust", "9x gtceu:zirconia_dust", "153x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/grossmanite_digestion")
        .itemInputs("10x gtceu:grossmanite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("2x gtceu:quicklime_dust", "3x gtceu:titanium_dioxide_mix_dust", "3x gtceu:corundum_dust", "3x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/astrophyllite_digestion")
        .itemInputs("39x gtceu:astrophyllite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("3x gtceu:potash_dust", "2x gtceu:villiaumite_dust", "7x gtceu:magnetite_dust", "16x gtceu:yellow_limonite_dust", "6x gtceu:titanium_dioxide_mix_dust",
            "12x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/umbite_digestion")
        .itemInputs("32x gtceu:umbite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("6x gtceu:potash_dust", "3x gtceu:zirconia_dust", "3x gtceu:titanium_dioxide_mix_dust", "18x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/senkevichite_digestion")
        .itemInputs("34x gtceu:senkevichite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("1x gtceu:caesium_dust", "3x gtceu:potassium_hydroxide_dust", "3x gtceu:sodium_hydroxide_dust", "4x gtceu:quicklime_dust", 
            "3x gtceu:titanium_dioxide_mix_dust", "21x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/jonesite_digestion")
        .itemInputs("64x gtceu:jonesite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("24x gtceu:barite_dust", "3x gtceu:potassium_hydroxide_dust", "3x gtceu:sodium_hydroxide_dust", "12x gtceu:titanium_dioxide_mix_dust",
            "5x gtceu:corundum_dust", "30x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .outputFluids("minecraft:water 5000")
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/neptunite_digestion")
        .itemInputs("40x gtceu:neptunite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("3x gtceu:potassium_hydroxide_dust", "6x gtceu:sodium_hydroxide_dust", "1x gtceu:lithium_dust", "5x gtceu:hematite_dust",
            "6x gtceu:titanium_dioxide_mix_dust", "24x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/qeltite_digestion")
        .itemInputs("23x gtceu:qeltite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("6x gtceu:quicklime_dust", "3x gtceu:titanium_dioxide_mix_dust", "9x gtceu:silicon_dioxide_dust", "5x gtceu:hematite_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/rippite_digestion")
        .itemInputs("22x gtceu:rippite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("3x gtceu:potassium_hydroxide_dust", "2x gtceu:carobbiite_dust", "4x gtceu:niobium_pentoxide_dust", "3x gtceu:titanium_dioxide_mix_dust", 
            "12x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/burpalite_digestion")
        .itemInputs("15x gtceu:burpalite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("4x gtceu:villiaumite_dust", "2x gtceu:quicklime_dust", "3x gtceu:zirconia_dust", "6x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/oneillite_digestion")
        .itemInputs("133x gtceu:oneillite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("2x gtceu:salt_dust", "42x gtceu:sodium_hydroxide_dust", "6x gtceu:quicklime_dust", "9x gtceu:pyrolusite_dust", "7x gtceu:magnetite_dust",
            "9x gtceu:zirconia_dust", "4x gtceu:niobium_pentoxide_dust", "75x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/aqualite_digestion")
        .itemInputs("141x gtceu:aqualite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("2x gtceu:salt_dust", "6x gtceu:sodium_hydroxide_dust", "3x gtceu:potassium_hydroxide_dust", "1x gtceu:strontium_dust", "30x gtceu:calcium_hydroxide_dust",
            "9x gtceu:zirconia_dust", "78x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .outputFluids("minecraft:water 8000")
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/lemoynite_digestion")
        .itemInputs("46x gtceu:lemoynite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("3x gtceu:sodium_hydroxide_dust", "3x gtceu:potassium_hydroxide_dust", "5x gtceu:calcium_hydroxide_dust", "6x gtceu:zirconia_dust",
            "30x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .outputFluids("minecraft:water 3000")
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])

    // Mo/Re Line
    // Ore digestion
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/dzhezkazganite_digestion")
        .itemInputs("1x gtceu:purified_dzhezkazganite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("6x gtceu:molybdenum_sludge_dust", "2x gtceu:galena_dust", "4x gtceu:chalcocite_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/tarkianite_digestion")
        .itemInputs("1x gtceu:purified_tarkianite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("8x gtceu:molybdenum_sludge_dust", "9x gtceu:rheniite_dust", "3x gtceu:chalcopyrite_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/rheniite_digestion")
        .itemInputs("1x gtceu:purified_rheniite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("6x gtceu:molybdenum_sludge_dust", "6x gtceu:rheniite_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/nickolayite_digestion")
        .itemInputs("1x gtceu:purified_nickolayite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("4x gtceu:molybdenum_sludge_dust", "2x gtceu:pyrite_dust", "1x gtceu:phosphorus_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/monipite_digestion")
        .itemInputs("1x gtceu:purified_monipite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("4x gtceu:molybdenum_sludge_dust", "2x gtceu:millerite_dust", "1x gtceu:phosphorus_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/hemusite_digestion")
        .itemInputs("1x gtceu:purified_hemusite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("3x gtceu:molybdenum_sludge_dust", "12x gtceu:chalcocite_dust", "3x gtceu:cassiterite_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/ferrodimolybdenite_digestion")
        .itemInputs("1x gtceu:purified_ferrodimolybdenite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("4x gtceu:molybdenum_sludge_dust", "2x gtceu:pyrite_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/castaingite_digestion")
        .itemInputs("1x gtceu:purified_castaingite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("4x gtceu:molybdenum_sludge_dust", "2x gtceu:chalcocite_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/molybdenite_digestion")
        .itemInputs("1x gtceu:purified_molybdenite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("6x gtceu:molybdenum_sludge_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/parkinsonite_digestion")
        .itemInputs("1x gtceu:purified_parkinsonite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("2x gtceu:molybdenum_sludge_dust", "14x gtceu:galena_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000", "gtceu:hydrochloric_acid 2000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/mosesite_digestion")
        .itemInputs("1x gtceu:purified_mosesite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("2x gtceu:molybdenum_sludge_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000", "gtceu:mercury 8000", "gtceu:nitrosyl_chloride 2000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/majindeite_digestion")
        .itemInputs("1x gtceu:purified_majindeite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("6x gtceu:molybdenum_sludge_dust", "1x gtceu:magnesium_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/iseite_digestion")
        .itemInputs("1x gtceu:purified_iseite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("6x gtceu:molybdenum_sludge_dust", "4x gtceu:alabandite_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/raydemarkite_digestion")
        .itemInputs("1x gtceu:purified_raydemarkite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("6x gtceu:molybdenum_sludge_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000", "minecraft:water 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/mourite_digestion")
        .itemInputs("1x gtceu:purified_mourite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("8x gtceu:molybdenum_sludge_dust", "3x gtceu:uraninite_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000", "minecraft:water 5000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/molybdomenite_digestion")
        .itemInputs("1x gtceu:purified_molybdomenite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("1x gtceu:molybdenum_sludge_dust", "2x gtceu:galena_dust")
        .outputFluids("gtceu:selenic_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/rhabdoborite_mo_digestion")
        .itemInputs("1x gtceu:purified_rhabdoborite_mo_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("2x gtceu:molybdenum_sludge_dust", "12x gtceu:magnesium_dust", "6x gtceu:boron_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000", "gtceu:hydrofluoric_acid 2000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/novikovite_digestion")
        .itemInputs("1x gtceu:purified_novikovite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("4x gtceu:molybdenum_sludge_dust", "8x gtceu:ammonium_sulfate_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/chiluite_digestion")
        .itemInputs("1x gtceu:purified_chiluite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("3x gtceu:molybdenum_sludge_dust", "8x gtceu:bismuthinite_dust")
        .outputFluids("gtceu:telluric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/downsite_digestion")
        .itemInputs("1x gtceu:purified_downsite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("4x gtceu:molybdenum_sludge_dust", "10x gtceu:potassium_sulfate_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/powellite_digestion")
        .itemInputs("1x gtceu:purified_powellite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("6x gtceu:molybdenum_sludge_dust", "2x gtceu:anhydrite_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/wulfenite_digestion")
        .itemInputs("1x gtceu:purified_wulfenite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("6x gtceu:molybdenum_sludge_dust", "2x gtceu:galena_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/huenite_digestion")
        .itemInputs("1x gtceu:purified_huenite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("4x gtceu:molybdenum_sludge_dust", "8x gtceu:chalcocite_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000", "minecraft:water 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/tancaite_ce_digestion")
        .itemInputs("1x gtceu:purified_tancaite_ce_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("4x gtceu:molybdenum_sludge_dust", "2x gtceu:pyrite_dust", "3x gtceu:ceria_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000", "minecraft:water 3000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/betpakdalite_nana_digestion")
        .itemInputs("1x gtceu:purified_betpakdalite_nana_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("6x gtceu:molybdenum_sludge_dust", "6x gtceu:pyrite_dust", "4x gtceu:realgar_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000", "minecraft:water 24000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/hereroite_digestion")
        .itemInputs("1x gtceu:purified_hereroite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("2x gtceu:molybdenum_sludge_dust", "192x gtceu:galena_dust", "14x gtceu:realgar_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000", "gtceu:hydrochloric_acid 30000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/sarrochite_digestion")
        .itemInputs("1x gtceu:purified_sarrochite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("6x gtceu:molybdenum_sludge_dust", "6x gtceu:pyrite_dust", "8x gtceu:tricalcium_phosphate_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000", "minecraft:water 38000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/melkovite_digestion")
        .itemInputs("1x gtceu:purified_melkovite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("6x gtceu:molybdenum_sludge_dust", "6x gtceu:pyrite_dust", "4x gtceu:tricalcium_phosphate_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000", "minecraft:water 21000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    // Mainline
    event.recipes.gtceu.electric_blast_furnace("kubejs:molybdenum_rhenium/oxide_blast")
        .itemInputs("1x gtceu:molybdenum_sludge_dust")
        .inputFluids("gtceu:oxygen 4000")
        .itemOutputs("1x gtceu:molybdenum_oxide_slag_dust") 
        .outputFluids("gtceu:sulfur_dioxide 2000")
        .duration(500).EUt(GTValues.VA[GTValues.EV]).blastFurnaceTemp(3200)
    event.recipes.gtceu.centrifuge("kubejs:molybdenum_rhenium/oxide_sep")
        .itemInputs("4x gtceu:molybdenum_oxide_slag_dust")
        .inputFluids("gtceu:distilled_water 1000")
        .itemOutputs("6x gtceu:impure_molybdenum_trioxide_dust", "2x gtceu:tungsten_trioxide_dust", "3x gtceu:rhenium_heptoxide_dust")
        .duration(220).EUt(GTValues.VA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/orthomolybdenate")
        .itemInputs("4x gtceu:impure_molybdenum_trioxide_dust")
        .inputFluids("gtceu:ammonia 2000", "minecraft:water 1000")
        .itemOutputs("15x gtceu:ammonium_orthomolybdate_dust")
        .duration(140).EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.large_chemical_reactor("kubejs:molybdenum_rhenium/dimolybdenate")
        .itemInputs("30x gtceu:ammonium_orthomolybdate_dust")
        .inputFluids("gtceu:sulfuric_acid 2000")
        .itemOutputs("19x gtceu:ammonium_dimolybdate_dust", "4x gtceu:chalcocite_dust")
        .outputFluids("gtceu:ammonia 2000", "minecraft:water 3000", "gtceu:oxygen 3000")
        .duration(230).EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.electric_blast_furnace("kubejs:molybdenum_rhenium/ammoniate_blast")
        .itemInputs("19x gtceu:ammonium_dimolybdate_dust", "gtceu:salt_dust")
        .itemOutputs("8x gtceu:molybdenum_trioxide_dust", "2x gtceu:hydrohalite_dust") 
        .outputFluids("gtceu:ammonia 2000")
        .duration(320).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(2600)
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/hydrogenation")
        .itemInputs("4x gtceu:molybdenum_trioxide_dust")
        .inputFluids("gtceu:hydrogen 3000")
        .itemOutputs("1x gtceu:molybdenum_dust")
        .outputFluids("minecraft:water 3000")
        .duration(300).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.electric_blast_furnace("kubejs:molybdenum_rhenium/rhenium_blast_1")
        .itemInputs("18x gtceu:rhenium_heptoxide_dust")
        .itemOutputs("12x gtceu:rhenium_dioxide_dust") 
        .outputFluids("gtceu:oxygen 6000")
        .duration(400).EUt(GTValues.VA[GTValues.LuV]).blastFurnaceTemp(5500)
    event.recipes.gtceu.electric_blast_furnace("kubejs:molybdenum_rhenium/rhenium_blast_2")
        .itemInputs("21x gtceu:rhenium_dioxide_dust")
        .itemOutputs("18x gtceu:rhenium_heptoxide_dust", "3x gtceu:rhenium_dust") 
        .duration(440).EUt(GTValues.VHA[GTValues.ZPM]).blastFurnaceTemp(7200)
    // Misc cleanup for un-decomposable byproduct dusts
    event.recipes.gtceu.electric_blast_furnace("kubejs:molybdenum_rhenium/cleanup_tarkianite")
        .itemInputs("26x gtceu:tarkianite_dust")
        .inputFluids("gtceu:oxygen 54000")
        .itemOutputs("2x gtceu:cupric_oxide_dust", "15x gtceu:rhenium_dioxide_dust", "12x gtceu:molybdenum_trioxide_dust") // Fe left out, no slots and not important
        .outputFluids("gtceu:sulfur_dioxide 16000")
        .duration(540).EUt(GTValues.VA[GTValues.LuV]).blastFurnaceTemp(5500)

    // Nb/Ta Line (TODO Eventually)
    var NbTaOres = [
        "jedwabite", "davidite_y", "tapiolite_mn", "tapiolite_fe", "samarskite_yb", "samarskite_y", "ixiolite_sc", "ixiolite_fe", "ixiolite_mn", "heftejernite",
        "tantalaeschynite_ce", "tantalite_mg", "tantalite_mn", "tantalite_fe", "columbite_mg", "columbite_mn", "columbite_fe", "wodginite", "aeschynite_ce",
        "aeschynite_nd", "aeschynite_y", "uranopolycrase", "euxenite_y", "foordite", "hydroxynatropyrochlore", "fluorcalciopyrochlore", "oxycalciopyrochlore",
        "fluorplumbopyrochlore", "stefanweissite", "laachite", "cesplumtantite", "ekebergite", "franconite", "behierite", "schiavinatoite", "fergusonite_ce",
        "fergusonite_nd", "fergusonite_y", "holtite", "nacareniobsite_ce", "nacareniobsite_nd", "roumaite", "saamite", "epistolite", "katanite", "nenadkevichite",
        "oneillite", "laurentianite", "rippite"
    ]
    // event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/jedwabite_digestion")
    //     .itemInputs("10x gtceu:jedwabite_dust")
    //     .inputFluids("gtceu:hydrofluoric_acid 1000")
    //     .itemOutputs("21x gtceu:iron_ii_fluoride_dust")
    //     .outputFluids()

    // UO2/Th Line
    var UranThOres = [
        "haitaite_la", "davidite_ce", "davidite_la", "uranopolycrase", "euxenite_y", "thorutite", "brannerite", "fluorplumbopyrochlore", "uraninite", "pitchblende",
        "thorianite", "ekebergite", "mourite", "schoepite", "studtite", "billietite", "sayrite", "curite", "spriggite", "margaritasite", "carnotite", "finchite",
        "vanuralite", "uvanite", "chadwickite", "seelite", "piretite", "cliffordite", "tuliokite", "wyartite", "sharpite", "bayleyite", "rabbittite", "linekite",
        "paddlewheelite", "voglite", "lepersonnite_gd", "lepersonnite_nd", "mathesiusite", "uranopilite", "bobcookite", "alwilkinsite_y", "greenlizardite",
        "seaborgite", "zippeite", "oppenheimerite", "ootannite", "uranotungstite", "grayite", "ningyoite", "urphoite", "saryakite_y", "ulrichite", "uranocircite",
        "torbernite", "przhevalskite", "uramphite", "uranosphathite", "coconinoite", "upalite", "francoisite_nd", "francoisite_ce", "kivuite", "althupite",
        "mundite", "coffinite", "thorite", "enalite", "vicanite", "uranophane", "barronite", "uranosilite", "phosinaite_ce", "ciprianiite", "ekanite", "uroxite"
    ]

    // Nq Line
    var NaqOres = [
        "enquedite", "enquedine", "enquedire", "kaemanite_rb", "kaemanite_cs", "kaemanite_ke", "queryl", "quarate", "xenocage"
    ]
    // TODO
    // 45x KeNq4Np2PbGeO29Si6H + 5000mb HBF4 + 36x SbF5 + 6000mb SO2HF2 ||
    // 6x KeBF4 + 28x NqBF5 + 10x NpF4 + 3x PbF2 + 5x GeF4 + 30x SiF4 + 6x Sb + 6000mb H2SO4 + 67000mb O2 ||

    // Misc digester dusts
    event.recipes.gtceu.ore_digestion("kubejs:misc_oreproc/digest_aleutite")
        .itemInputs("152x gtceu:aleutite_dust")
        .chancedFluidInput("gtceu:hydrochloric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("86x gtceu:cupric_oxide_dust", "32x gtceu:arsenic_trioxide_dust", "28x gtceu:vanadium_pentoxide_dust", "4x gtceu:rock_salt_dust",
            "2x gtceu:massicot_dust", "2x gtceu:rubidium_chloride_dust", "2x gtceu:caesium_chloride_dust")
        .chancedFluidOutput("gtceu:diluted_hydrochloric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(700).EUt(GTValues.VHA[GTValues.EV])
})