ServerEvents.recipes(event => {
    // Tungsten processing hardmode changes
    event.remove({ id: "gtceu:electrolyzer/tungstic_acid_electrolysis" })

    event.recipes.gtceu.extractor("kubejs:tungsten_trioxide_dust")
        .itemInputs("7x #forge:dusts/tungstic_acid")
        .itemOutputs("4x gtceu:tungsten_trioxide_dust")
        .outputFluids(Fluid.of("minecraft:water", 1000))
        .duration(160).EUt(16)

    event.recipes.gtceu.electric_blast_furnace("kubejs:hot_tungsten_ingot")
        .itemInputs("8x #forge:dusts/tungsten_trioxide", "3x #forge:dusts/carbon")
        .itemOutputs("2x gtceu:hot_tungsten_ingot")
        .outputFluids(Fluid.of("gtceu:carbon_dioxide", 3000))
        .blastFurnaceTemp(3600)
        .duration(2400).EUt(1920)

    event.recipes.gtceu.chemical_reactor("kubejs:tungsten_dust")
        .itemInputs("4x #forge:dusts/tungsten_trioxide")
        .inputFluids(Fluid.of("gtceu:hydrogen", 6000))
        .itemOutputs("gtceu:tungsten_dust")
        .outputFluids(Fluid.of("water", 3000))
        .duration(210).EUt(960)

    // Tungsten line ores
    // Hubnerite (6 MnWO4 + 2 HCl -> 7 H2WO4 + 3 MnCl2)
    event.recipes.gtceu.chemical_bath("kubejs:tungstenline/hubnerite")
        .itemInputs("6x gtceu:hubnerite_dust")
        .inputFluids("gtceu:hydrochloric_acid 2000")
        .itemOutputs("7x gtceu:tungstic_acid_dust", "3x gtceu:manganese_chloride_dust")
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(210)
    // Ferberite (6 FeWO4 + 2 HCl -> 7 H2WO4 + 3 FeCl2)
    event.recipes.gtceu.chemical_bath("kubejs:tungstenline/ferberite")
        .itemInputs("6x gtceu:ferberite_dust")
        .inputFluids("gtceu:hydrochloric_acid 2000")
        .itemOutputs("7x gtceu:tungstic_acid_dust", "3x gtceu:iron_ii_chloride_dust")
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(210)
    // Krasnoselskite (6 CoWO4 + 2 HCl -> 7 H2WO4 + 3 CoCl2)
    event.recipes.gtceu.chemical_bath("kubejs:tungstenline/krasnoselskite")
        .itemInputs("6x gtceu:krasnoselskite_dust")
        .inputFluids("gtceu:hydrochloric_acid 2000")
        .itemOutputs("7x gtceu:tungstic_acid_dust", "3x gtceu:cobalt_chloride_dust")
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(210)
    // Stolzite (6 PbWO4 + 2 HCl -> 7 H2WO4 + 3 PbCl2)
    event.recipes.gtceu.chemical_bath("kubejs:tungstenline/stolzite")
        .itemInputs("6x gtceu:stolzite_dust")
        .inputFluids("gtceu:hydrochloric_acid 2000")
        .itemOutputs("7x gtceu:tungstic_acid_dust", "3x gtceu:lead_chloride_dust")
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(210)
    // Russellite (27 Bi2WO6 + 6 HCl -> 21 H2WO4 + 8 BiCl3 + 10 Bi2O3)
    event.recipes.gtceu.chemical_bath("kubejs:tungstenline/russellite")
        .itemInputs("27x gtceu:russellite_dust")
        .inputFluids("gtceu:hydrochloric_acid 6000")
        .itemOutputs("21x gtceu:tungstic_acid_dust", "8x gtceu:bismuth_chloride_dust", "10x gtceu:bismite_dust")
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(630)
    // Tungstite (5 WO3(H2O) + 1 HCl -> 4 WO3 + 2 (HCl)(H2O))
    event.recipes.gtceu.chemical_bath("kubejs:tungstenline/tungstite")
        .itemInputs("5x gtceu:tungstite_dust")
        .inputFluids("gtceu:hydrochloric_acid 1000")
        .itemOutputs("4x gtceu:tungsten_trioxide_dust")
        .outputFluids("gtceu:diluted_hydrochloric_acid 2000")
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(210)
    // Hydrotungstite (6 WO3(H2O)2 + 2 HCl -> 4 WO3 + 4 (HCl)(H2O))
    event.recipes.gtceu.chemical_bath("kubejs:tungstenline/hydrotungstite")
        .itemInputs("6x gtceu:hydrotungstite_dust")
        .inputFluids("gtceu:hydrochloric_acid 2000")
        .itemOutputs("4x gtceu:tungsten_trioxide_dust")
        .outputFluids("gtceu:diluted_hydrochloric_acid 4000")
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(210)
    // Yttrotungstite-(Ce) (15 CeW2O9H3 + 3 HCl -> 14 H2WO4 + 4 CeCl3 + H2O) -> Init CeCl3
    event.recipes.gtceu.chemical_bath("kubejs:tungstenline/yttrotungstite_ce")
        .itemInputs("15x gtceu:yttrotungstite_ce_dust")
        .inputFluids("gtceu:hydrochloric_acid 3000")
        .itemOutputs("14x gtceu:tungstic_acid_dust", "4x gtceu:cerium_trichloride_dust")
        .outputFluids("minecraft:water 1000")
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(420)
    // Yttrotungstite-(Y) (15 YW2O9H3 + 3 HCl -> 14 H2WO4 + 4 YCl3 + H2O) -> Init YCl3
    event.recipes.gtceu.chemical_bath("kubejs:tungstenline/yttrotungstite_y")
        .itemInputs("15x gtceu:yttrotungstite_y_dust")
        .inputFluids("gtceu:hydrochloric_acid 3000")
        .itemOutputs("14x gtceu:tungstic_acid_dust", "4x gtceu:yttrium_trichloride_dust")
        .outputFluids("minecraft:water 1000")
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(420)
    // Anthoinite (11 AlWO6H3 + 3 HCl -> 7 H2WO4 + 4 AlCl3 + H2O)
    event.recipes.gtceu.chemical_bath("kubejs:tungstenline/anthoinite")
        .itemInputs("11x gtceu:anthoinite_dust")
        .inputFluids("gtceu:hydrochloric_acid 3000")
        .itemOutputs("7x gtceu:tungstic_acid_dust", "4x gtceu:aluminium_chloride_dust")
        .outputFluids("minecraft:water 1000")
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(210)
    // Ootannite (27 Th2W4O16(H2O)5 + 5 HCl -> 28 H2WO4 + 10 (H2O)(HCl) + 2 Th)
    event.recipes.gtceu.chemical_bath("kubejs:tungstenline/ootannite")
        .itemInputs("27x gtceu:ootannite_dust")
        .inputFluids("gtceu:hydrochloric_acid 5000")
        .itemOutputs("28x gtceu:tungstic_acid_dust", "2x gtceu:thorium_232_dust")
        .outputFluids("gtceu:diluted_hydrochloric_acid 10000")
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(840)
    
    // Remaining tungsten dusts (more complex, need customized decomps)
    event.recipes.gtceu.electric_blast_furnace("kubejs:tungsten/tungstenite_blasting")
        .itemInputs("3x gtceu:tungstenite_dust")
        .inputFluids("gtceu:oxygen 4000")
        .itemOutputs("1x gtceu:hot_tungsten_ingot")
        .outputFluids("gtceu:sulfur_dioxide 2000")
        .blastFurnaceTemp(3600)
        .duration(2400).EUt(1920)
    event.recipes.gtceu.electric_blast_furnace("kubejs:tungsten/catamarcaite_blasting")
        .itemInputs("16x gtceu:catamarcaite_dust")
        .inputFluids("gtceu:oxygen 16000")
        .itemOutputs("12x minecraft:copper_ingot", "1x gtceu:tin_ingot", "1x gtceu:hot_tungsten_ingot")
        .outputFluids("gtceu:sulfur_dioxide 8000")
        .blastFurnaceTemp(3600)
        .duration(2400).EUt(1920)
    event.recipes.gtceu.ore_digestion("kubejs:tungsten/ophirite_digestion")
        .itemInputs("146x gtceu:ophirite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:hydrochloric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("4x gtceu:quicklime_dust", "8x gtceu:magnesia_dust", "4x gtceu:zincite_dust", "6x gtceu:pyrolusite_dust", "5x gtceu:hematite_dust", "126x gtceu:tungstic_acid_dust")
        .chancedFluidOutput("gtceu:diluted_hydrochloric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1200).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:tungsten/uranotungstite_digestion")
        .itemInputs("23x gtceu:uranotungstite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:hydrochloric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("6x gtceu:barite_dust", "2x gtceu:massicot_dust", "2x gtceu:uraninite_dust", "7x gtceu:tungstic_acid_dust", "5x gtceu:goethite_dust")
        .chancedFluidOutput("gtceu:diluted_hydrochloric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1200).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:tungsten/natrowalentaite_digestion")
        .itemInputs("29x gtceu:natrowalentaite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:hydrochloric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("7x gtceu:magnetite_dust", "4x gtceu:salt_dust", "5x gtceu:arsenic_trioxide_dust", "7x gtceu:tungstic_acid_dust", "2x gtceu:phosphate_dust")
        .chancedFluidOutput("gtceu:diluted_hydrochloric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1200).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:tungsten/johnsenite_ce_digestion")
        .itemInputs("136x gtceu:johnsenite_ce_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:hydrochloric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("6x gtceu:sodium_bicarbonate_dust", "22x gtceu:salt_dust", "6x gtceu:ceria_dust", "9x gtceu:pyrolusite_dust", "9x gtceu:zirconia_dust",
            "75x gtceu:silicon_dioxide_dust", "7x gtceu:tungstic_acid_dust")
        .chancedFluidOutput("gtceu:diluted_hydrochloric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1200).EUt(GTValues.VHA[GTValues.IV])

    // Indium line combinations
    var indiOres = Array.from(new Set([
        "galena", "sphalerite", "alburnite", "xuwenyuanite", "acanthite", "spryite", "argentite", "aguilarite", "cervelleite", "fischesserite", "sopcheite", "ruizhongite",
        "laforetite", "empressite", "sylvanite", "pyrargyrite", "xanthoconite", "samsonite", "laffittite", "stephanite", "quadratite", "manganoquadratite", "interliveingite",
        "rathite", "veenite", "sartorite", "heptasartorite", "polloneite", "boulangerite", "buynite", "cylindrite", "oscarkempffite", "diaphorite", "jordanite", "geocronite",
        "stilleite"
    ]))
    const seenIndiumPairs = new Set()
    indiOres.forEach((ore1, index) => {
        indiOres.forEach((ore2, i) => {
            const pairKey = [ore1, ore2].sort().join("_")
            if (!(pairKey === "galena_sphalerite" || seenIndiumPairs.has(pairKey) || ore1 === ore2)) {
                seenIndiumPairs.add(pairKey)
                event.recipes.gtceu.mixer(`kubejs:indiumline/${ore1}_${ore2}`)
                    .itemInputs(`gtceu:purified_${ore1}_ore`, `gtceu:purified_${ore2}_ore`)
                    .inputFluids("gtceu:sulfuric_acid 4000")
                    .outputFluids("gtceu:indium_concentrate 1000")
                    .EUt(150)
                    .duration(60)
            }
        })
    })

    // Misc digester dusts
    event.recipes.gtceu.ore_digestion("kubejs:misc_oreproc/digest_aleutite")
        .itemInputs("152x gtceu:aleutite_dust")
        .chancedFluidInput("gtceu:hydrochloric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("86x gtceu:cupric_oxide_dust", "32x gtceu:arsenic_trioxide_dust", "28x gtceu:vanadium_pentoxide_dust", "4x gtceu:rock_salt_dust",
            "2x gtceu:massicot_dust", "2x gtceu:rubidium_chloride_dust", "2x gtceu:caesium_chloride_dust")
        .chancedFluidOutput("gtceu:diluted_hydrochloric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(700).EUt(GTValues.VHA[GTValues.EV])
})