ServerEvents.recipes(event => {
    // Mo/Re Line
    // Ore digestion
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/dzhezkazganite_digestion")
        .itemInputs("1x gtceu:purified_dzhezkazganite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("6x gtceu:molybdenum_sludge_dust", "2x gtceu:galena_dust", "4x gtceu:chalcocite_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/tarkianite_digestion")
        .itemInputs("1x gtceu:purified_tarkianite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("8x gtceu:molybdenum_sludge_dust", "9x gtceu:rheniite_dust", "3x gtceu:chalcopyrite_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/rheniite_digestion")
        .itemInputs("1x gtceu:purified_rheniite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("6x gtceu:molybdenum_sludge_dust", "6x gtceu:rheniite_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/nickolayite_digestion")
        .itemInputs("1x gtceu:purified_nickolayite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("4x gtceu:molybdenum_sludge_dust", "2x gtceu:pyrite_dust", "1x gtceu:phosphorus_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/monipite_digestion")
        .itemInputs("1x gtceu:purified_monipite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("4x gtceu:molybdenum_sludge_dust", "2x gtceu:millerite_dust", "1x gtceu:phosphorus_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/hemusite_digestion")
        .itemInputs("1x gtceu:purified_hemusite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("3x gtceu:molybdenum_sludge_dust", "12x gtceu:chalcocite_dust", "3x gtceu:cassiterite_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/ferrodimolybdenite_digestion")
        .itemInputs("1x gtceu:purified_ferrodimolybdenite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("4x gtceu:molybdenum_sludge_dust", "2x gtceu:pyrite_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/castaingite_digestion")
        .itemInputs("1x gtceu:purified_castaingite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("4x gtceu:molybdenum_sludge_dust", "2x gtceu:chalcocite_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/molybdenite_digestion")
        .itemInputs("1x gtceu:purified_molybdenite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("6x gtceu:molybdenum_sludge_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/parkinsonite_digestion")
        .itemInputs("1x gtceu:purified_parkinsonite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("2x gtceu:molybdenum_sludge_dust", "14x gtceu:galena_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000", "gtceu:hydrochloric_acid 2000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/mosesite_digestion")
        .itemInputs("1x gtceu:purified_mosesite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("2x gtceu:molybdenum_sludge_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000", "gtceu:mercury 8000", "gtceu:nitrosyl_chloride 2000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/majindeite_digestion")
        .itemInputs("1x gtceu:purified_majindeite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("6x gtceu:molybdenum_sludge_dust", "1x gtceu:magnesium_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/iseite_digestion")
        .itemInputs("1x gtceu:purified_iseite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("6x gtceu:molybdenum_sludge_dust", "4x gtceu:alabandite_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/raydemarkite_digestion")
        .itemInputs("1x gtceu:purified_raydemarkite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("6x gtceu:molybdenum_sludge_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000", "minecraft:water 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/mourite_digestion")
        .itemInputs("1x gtceu:purified_mourite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("8x gtceu:molybdenum_sludge_dust", "3x gtceu:uraninite_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000", "minecraft:water 5000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/molybdomenite_digestion")
        .itemInputs("1x gtceu:purified_molybdomenite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("1x gtceu:molybdenum_sludge_dust", "2x gtceu:galena_dust")
        .outputFluids("gtceu:selenic_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/rhabdoborite_mo_digestion")
        .itemInputs("1x gtceu:purified_rhabdoborite_mo_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("2x gtceu:molybdenum_sludge_dust", "12x gtceu:magnesium_dust", "6x gtceu:boron_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000", "gtceu:hydrofluoric_acid 2000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/novikovite_digestion")
        .itemInputs("1x gtceu:purified_novikovite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("4x gtceu:molybdenum_sludge_dust", "8x gtceu:ammonium_sulfate_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/chiluite_digestion")
        .itemInputs("1x gtceu:purified_chiluite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("3x gtceu:molybdenum_sludge_dust", "8x gtceu:bismuthinite_dust")
        .outputFluids("gtceu:telluric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/downsite_digestion")
        .itemInputs("1x gtceu:purified_downsite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("4x gtceu:molybdenum_sludge_dust", "10x gtceu:potassium_sulfate_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/powellite_digestion")
        .itemInputs("1x gtceu:purified_powellite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("6x gtceu:molybdenum_sludge_dust", "2x gtceu:anhydrite_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/wulfenite_digestion")
        .itemInputs("1x gtceu:purified_wulfenite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("6x gtceu:molybdenum_sludge_dust", "2x gtceu:galena_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/huenite_digestion")
        .itemInputs("1x gtceu:purified_huenite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("4x gtceu:molybdenum_sludge_dust", "8x gtceu:chalcocite_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000", "minecraft:water 1000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/tancaite_ce_digestion")
        .itemInputs("1x gtceu:purified_tancaite_ce_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("4x gtceu:molybdenum_sludge_dust", "2x gtceu:pyrite_dust", "3x gtceu:ceria_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000", "minecraft:water 3000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/betpakdalite_nana_digestion")
        .itemInputs("1x gtceu:purified_betpakdalite_nana_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("6x gtceu:molybdenum_sludge_dust", "6x gtceu:pyrite_dust", "4x gtceu:realgar_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000", "minecraft:water 24000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/hereroite_digestion")
        .itemInputs("1x gtceu:purified_hereroite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("2x gtceu:molybdenum_sludge_dust", "192x gtceu:galena_dust", "14x gtceu:realgar_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000", "gtceu:hydrochloric_acid 30000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/sarrochite_digestion")
        .itemInputs("1x gtceu:purified_sarrochite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("6x gtceu:molybdenum_sludge_dust", "6x gtceu:pyrite_dust", "8x gtceu:tricalcium_phosphate_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000", "minecraft:water 38000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/melkovite_digestion")
        .itemInputs("1x gtceu:purified_melkovite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("6x gtceu:molybdenum_sludge_dust", "6x gtceu:pyrite_dust", "4x gtceu:tricalcium_phosphate_dust")
        .outputFluids("gtceu:sulfuric_copper_solution 1000", "minecraft:water 21000")
        .duration(190).EUt(GTValues.VHA[GTValues.HV])
    // Mainline
    event.recipes.gtceu.electric_blast_furnace("kubejs:molybdenum_rhenium/oxide_blast")
        .itemInputs("1x gtceu:molybdenum_sludge_dust")
        .inputFluids("gtceu:oxygen 4000")
        .itemOutputs("1x gtceu:molybdenum_oxide_slag_dust") 
        .outputFluids("gtceu:sulfur_dioxide 2000")
        .duration(500).EUt(GTValues.VA[GTValues.EV]).blastFurnaceTemp(3200)
    event.recipes.gtceu.centrifuge("kubejs:molybdenum_rhenium/oxide_sep")
        .itemInputs("4x gtceu:molybdenum_oxide_slag_dust")
        .inputFluids("gtceu:distilled_water 1000")
        .itemOutputs("6x gtceu:impure_molybdenum_trioxide_dust", "2x gtceu:tungsten_trioxide_dust", "3x gtceu:rhenium_heptoxide_dust")
        .duration(220).EUt(GTValues.VA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/orthomolybdenate")
        .itemInputs("4x gtceu:impure_molybdenum_trioxide_dust")
        .inputFluids("gtceu:ammonia 2000", "minecraft:water 1000")
        .itemOutputs("15x gtceu:ammonium_orthomolybdate_dust")
        .duration(140).EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.large_chemical_reactor("kubejs:molybdenum_rhenium/dimolybdenate")
        .itemInputs("30x gtceu:ammonium_orthomolybdate_dust")
        .inputFluids("gtceu:sulfuric_acid 2000")
        .itemOutputs("19x gtceu:ammonium_dimolybdate_dust", "4x gtceu:chalcocite_dust")
        .outputFluids("gtceu:ammonia 2000", "minecraft:water 3000", "gtceu:oxygen 3000")
        .duration(230).EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.electric_blast_furnace("kubejs:molybdenum_rhenium/ammoniate_blast")
        .itemInputs("19x gtceu:ammonium_dimolybdate_dust", "gtceu:salt_dust")
        .itemOutputs("8x gtceu:molybdenum_trioxide_dust", "2x gtceu:hydrohalite_dust") 
        .outputFluids("gtceu:ammonia 2000")
        .duration(320).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(2600)
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_rhenium/hydrogenation")
        .itemInputs("4x gtceu:molybdenum_trioxide_dust")
        .inputFluids("gtceu:hydrogen 3000")
        .itemOutputs("1x gtceu:molybdenum_dust")
        .outputFluids("minecraft:water 3000")
        .duration(300).EUt(GTValues.VHA[GTValues.HV])
    event.recipes.gtceu.electric_blast_furnace("kubejs:molybdenum_rhenium/rhenium_blast_1")
        .itemInputs("18x gtceu:rhenium_heptoxide_dust")
        .itemOutputs("12x gtceu:rhenium_dioxide_dust") 
        .outputFluids("gtceu:oxygen 6000")
        .duration(400).EUt(GTValues.VA[GTValues.LuV]).blastFurnaceTemp(5500)
    event.recipes.gtceu.electric_blast_furnace("kubejs:molybdenum_rhenium/rhenium_blast_2")
        .itemInputs("21x gtceu:rhenium_dioxide_dust")
        .itemOutputs("18x gtceu:rhenium_heptoxide_dust", "3x gtceu:rhenium_dust") 
        .duration(440).EUt(GTValues.VHA[GTValues.ZPM]).blastFurnaceTemp(7200)
    // Misc cleanup for un-decomposable byproduct dusts
    event.recipes.gtceu.electric_blast_furnace("kubejs:molybdenum_rhenium/cleanup_tarkianite")
        .itemInputs("26x gtceu:tarkianite_dust")
        .inputFluids("gtceu:oxygen 54000")
        .itemOutputs("2x gtceu:cupric_oxide_dust", "15x gtceu:rhenium_dioxide_dust", "12x gtceu:molybdenum_trioxide_dust") // Fe left out, no slots and not important
        .outputFluids("gtceu:sulfur_dioxide 16000")
        .duration(540).EUt(GTValues.VA[GTValues.LuV]).blastFurnaceTemp(5500)
})