ServerEvents.recipes(event => {
    // Nb/Ta Line
    var NbTaOres = [
        "jedwabite", "tapiolite_mn", "tapiolite_fe", "samarskite_yb", "samarskite_y", "ixiolite_sc", "ixiolite_fe", "ixiolite_mn", "heftejernite",
        "tantalite_mg", "tantalite_mn", "tantalite_fe", "columbite_mg", "columbite_mn", "columbite_fe", "wodginite",
        "foordite", "hydroxynatropyrochlore", "fluorcalciopyrochlore", "oxycalciopyrochlore",
        "fluorplumbopyrochlore", "cesplumtantite", "ekebergite", "franconite", "behierite", "schiavinatoite", "fergusonite_ce",
        "fergusonite_nd", "fergusonite_y", "holtite", "nacareniobsite_ce", "nacareniobsite_nd", "katanite", "nenadkevichite", "laurentianite"
    ]
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/jedwabite_digestion")
        .itemInputs("10x gtceu:jedwabite_dust")
        .inputFluids("gtceu:hydrofluoric_acid 6000", "gtceu:fluorine 29000")
        .itemOutputs("21x gtceu:iron_ii_fluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 3000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/tapiolite_fe_digestion")
        .itemInputs("9x gtceu:tapiolite_fe_dust")
        .inputFluids("gtceu:hydrofluoric_acid 16000")
        .itemOutputs("3x gtceu:iron_ii_fluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 2000", "minecraft:water 6000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/tapiolite_mn_digestion")
        .itemInputs("9x gtceu:tapiolite_mn_dust")
        .inputFluids("gtceu:hydrofluoric_acid 16000")
        .itemOutputs("3x gtceu:manganese_ii_fluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 2000", "minecraft:water 6000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/ixiolite_sc_digestion")
        .itemInputs("9x gtceu:ixiolite_sc_dust")
        .inputFluids("gtceu:hydrofluoric_acid 16000", "gtceu:fluorine 1000")
        .itemOutputs("4x gtceu:scandium_fluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 2000", "minecraft:water 6000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/ixiolite_fe_digestion")
        .itemInputs("9x gtceu:ixiolite_fe_dust")
        .inputFluids("gtceu:hydrofluoric_acid 16000")
        .itemOutputs("3x gtceu:iron_ii_fluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 2000", "minecraft:water 6000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/ixiolite_mn_digestion")
        .itemInputs("9x gtceu:ixiolite_mn_dust")
        .inputFluids("gtceu:hydrofluoric_acid 16000")
        .itemOutputs("3x gtceu:manganese_ii_fluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 2000", "minecraft:water 6000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/heftetjernite_digestion")
        .itemInputs("9x gtceu:heftetjernite_dust")
        .inputFluids("gtceu:hydrofluoric_acid 16000", "gtceu:fluorine 1000")
        .itemOutputs("4x gtceu:scandium_fluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 2000", "minecraft:water 6000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/tantalite_mn_digestion")
        .itemInputs("9x gtceu:tantalite_dust")
        .inputFluids("gtceu:hydrofluoric_acid 16000")
        .itemOutputs("3x gtceu:manganese_ii_fluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 2000", "minecraft:water 6000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/tantalite_fe_digestion")
        .itemInputs("9x gtceu:tantalite_fe_dust")
        .inputFluids("gtceu:hydrofluoric_acid 16000")
        .itemOutputs("3x gtceu:iron_ii_fluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 2000", "minecraft:water 6000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/tantalite_mg_digestion")
        .itemInputs("18x gtceu:tantalite_mg_dust")
        .inputFluids("gtceu:hydrofluoric_acid 32000")
        .itemOutputs("3x gtceu:iron_ii_fluoride_dust", "3x gtceu:magnesium_fluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 4000", "minecraft:water 12000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/columbite_fe_digestion")
        .itemInputs("9x gtceu:columbite_fe_dust")
        .inputFluids("gtceu:hydrofluoric_acid 16000")
        .itemOutputs("3x gtceu:iron_ii_fluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 2000", "minecraft:water 6000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/columbite_mn_digestion")
        .itemInputs("9x gtceu:columbite_mn_dust")
        .inputFluids("gtceu:hydrofluoric_acid 16000")
        .itemOutputs("3x gtceu:manganese_ii_fluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 2000", "minecraft:water 6000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/columbite_mg_digestion")
        .itemInputs("36x gtceu:tapiolite_mn_dust")
        .inputFluids("gtceu:hydrofluoric_acid 64000")
        .itemOutputs("3x gtceu:manganese_ii_fluoride_dust", "3x gtceu:iron_ii_fluoride_dust", "6x gtceu:magnesium_fluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 8000", "minecraft:water 24000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/foordite_digestion")
        .itemInputs("9x gtceu:foordite_dust")
        .inputFluids("gtceu:hydrofluoric_acid 16000")
        .itemOutputs("3x gtceu:tin_fluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 2000", "minecraft:water 6000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/samarskite_yb_digestion")
        .itemInputs("12x gtceu:samarskite_yb_dust")
        .inputFluids("gtceu:hydrofluoric_acid 18000", "gtceu:hydrogen 2000")
        .itemOutputs("3x gtceu:iron_ii_fluoride_dust", "3x gtceu:ytterbium_ii_fluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 2000", "minecraft:water 8000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/samarskite_y_digestion")
        .itemInputs("12x gtceu:samarskite_yb_dust")
        .inputFluids("gtceu:hydrofluoric_acid 19000", "gtceu:hydrogen 1000")
        .itemOutputs("3x gtceu:iron_ii_fluoride_dust", "4x gtceu:yttrium_fluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 2000", "minecraft:water 8000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/wodginite_digestion")
        .itemInputs("12x gtceu:wodginite_dust")
        .inputFluids("gtceu:hydrofluoric_acid 18000", "gtceu:hydrogen 2000")
        .itemOutputs("3x gtceu:manganese_ii_fluoride_dust", "3x gtceu:tin_fluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 2000", "minecraft:water 8000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/ekebergite_digestion")
        .itemInputs("12x gtceu:ekebergite_dust")
        .inputFluids("gtceu:hydrofluoric_acid 20000")
        .itemOutputs("3x gtceu:iron_ii_fluoride_dust", "5x gtceu:thorium_fluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 2000", "minecraft:water 8000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/behierite_digestion")
        .itemInputs("6x gtceu:behierite_dust")
        .inputFluids("gtceu:hydrofluoric_acid 10000")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 1000", "gtceu:boron_trifluoride 1000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/schiavinatoite_digestion")
        .itemInputs("6x gtceu:schiavinatoite_dust")
        .inputFluids("gtceu:hydrofluoric_acid 10000")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 1000", "gtceu:boron_trifluoride 1000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/fergusonite_nd_digestion")
        .itemInputs("6x gtceu:fergusonite_nd_dust")
        .inputFluids("gtceu:hydrofluoric_acid 10000")
        .itemOutputs("4x gtceu:neodymium_trifluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 1000", "minecraft:water 4000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/fergusonite_y_digestion")
        .itemInputs("6x gtceu:fergusonite_y_dust")
        .inputFluids("gtceu:hydrofluoric_acid 10000")
        .itemOutputs("4x gtceu:yttrium_fluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 1000", "minecraft:water 4000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/fergusonite_ce_digestion")
        .itemInputs("7x gtceu:fergusonite_ce_dust")
        .inputFluids("gtceu:hydrofluoric_acid 10000")
        .itemOutputs("4x gtceu:cerium_trifluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 1000", "minecraft:water 5000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/fluorcalciopyrochlore_digestion")
        .itemInputs("11x gtceu:pyrochlore_dust")
        .inputFluids("gtceu:hydrofluoric_acid 16000", "gtceu:fluorine 1000")
        .itemOutputs("6x gtceu:fluorite_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 2000", "minecraft:water 6000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/oxycalciopyrochlore_digestion")
        .itemInputs("11x gtceu:oxycalciopyrochlore_dust")
        .inputFluids("gtceu:hydrofluoric_acid 16000")
        .itemOutputs("6x gtceu:fluorite_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 2000", "minecraft:water 6000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/hydroxynatropyrochlore_digestion")
        .itemInputs("24x gtceu:hydroxynatropyrochlore_dust")
        .inputFluids("gtceu:hydrofluoric_acid 34000", "gtceu:fluorine 1000")
        .itemOutputs("4x gtceu:villiaumite_dust", "3x gtceu:fluorite_dust", "4x gtceu:cerium_trifluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 4000", "minecraft:water 14000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/fluorplumbopyrochlore_digestion")
        .itemInputs("44x gtceu:fluorplumbopyrochlore_dust")
        .inputFluids("gtceu:hydrofluoric_acid 54000", "gtceu:hydrogen 4000")
        .itemOutputs("6x gtceu:lead_ii_fluoride_dust", "8x gtceu:yttrium_fluoride_dust", "5x gtceu:thorium_fluoride_dust", 
            "5x gtceu:uranium_tetrafluoride_dust", "4x gtceu:titanium_trifluoride_dust", "3x gtceu:fluorite_dust") // Sodium lost to compression
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 5000", "minecraft:water 24000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/franconite_digestion")
        .itemInputs("13x gtceu:franconite_dust")
        .inputFluids("gtceu:hydrofluoric_acid 15000")
        .itemOutputs("2x gtceu:villiaumite_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 2000", "minecraft:water 9000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/holtite_digestion")
        .itemInputs("32x gtceu:holtite_dust")
        .inputFluids("gtceu:hydrofluoric_acid 40000")
        .itemOutputs("24x gtceu:aluminium_fluoride_dust", "15x gtceu:silicon_tetrafluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 1000", "gtceu:boron_trifluoride 1000") // OH lost
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/katanite_digestion")
        .itemInputs("23x gtceu:katanite_dust")
        .inputFluids("gtceu:hydrofluoric_acid 27000", "gtceu:hydrogen 3000")
        .itemOutputs("9x gtceu:barium_fluoride_dust", "9x gtceu:iron_ii_fluoride_dust", "10x gtceu:silicon_tetrafluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 1000", "minecraft:water 14000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/cesplumtantite_digestion")
        .itemInputs("37x gtceu:cesplumtantite_dust") 
        .inputFluids("gtceu:hydrofluoric_acid 64000", "gtceu:fluorine 1000")
        .itemOutputs("2x gtceu:caesium_fluoride_dust", "2x gtceu:villiaumite_dust", "6x gtceu:lead_ii_fluoride_dust", "4x gtceu:antimony_trifluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 8000", "minecraft:water 24000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/nenadkevichite_digestion")
        .itemInputs("54x gtceu:nenadkevichite_dust")
        .inputFluids("gtceu:hydrofluoric_acid 57000", "gtceu:hydrogen 6000")
        .itemOutputs("10x gtceu:villiaumite_dust", "40x gtceu:silicon_tetrafluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 4000", "minecraft:water 36000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/laurentianite_digestion")
        .itemInputs("36x gtceu:laurentianite_dust")
        .inputFluids("gtceu:hydrofluoric_acid 40000")
        .itemOutputs("6x gtceu:villiaumite_dust", "20x gtceu:silicon_tetrafluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 3000", "minecraft:water 26000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/nacareniobsite_nd_digestion")
        .itemInputs("30x gtceu:nacareniobsite_nd_dust")
        .inputFluids("gtceu:hydrofluoric_acid 32000")
        .itemOutputs("9x gtceu:fluorite_dust", "4x gtceu:neodymium_trifluoride_dust", "6x gtceu:villiaumite_dust", "20x gtceu:silicon_tetrafluoride_dust")
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 1000", "minecraft:water 15000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)
    event.recipes.gtceu.chemical_bath("kubejs:niobium_tantalum/nacareniobsite_ce_digestion") // REE -> cerium for ease
        .itemInputs("60x gtceu:nacareniobsite_nd_dust")
        .inputFluids("gtceu:hydrofluoric_acid 64000")
        .itemOutputs("18x gtceu:fluorite_dust", "8x gtceu:cerium_trifluoride_dust", "12x gtceu:villiaumite_dust", "40x gtceu:silicon_tetrafluoride_dust") 
        .outputFluids("gtceu:hydrogen_heptafluoride_metal_mixture 2000", "minecraft:water 30000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(500)

    event.recipes.gtceu.large_chemical_reactor("kubejs:niobium_tantalum/process_tantalum")
        .inputFluids("gtceu:hydrogen_heptafluorotantalate 1000", "gtceu:distilled_water 5000", "gtceu:ammonia 7000")
        .itemOutputs("12x gtceu:tantalum_pentoxide_hydrate_dust", "14x gtceu:ammonium_fluoride_dust")
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(380)
    event.recipes.gtceu.large_chemical_reactor("kubejs:niobium_tantalum/process_niobium")
        .inputFluids("gtceu:hydrogen_heptafluoroniobate 1000", "gtceu:distilled_water 5000", "gtceu:ammonia 7000")
        .itemOutputs("12x gtceu:niobium_pentoxide_hydrate_dust", "14x gtceu:ammonium_fluoride_dust")
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(380)
    event.recipes.gtceu.electric_blast_furnace("kubejs:niobium_tantalum/calcinate_tantalum")
        .itemInputs("12x gtceu:tantalum_pentoxide_hydrate_dust")
        .itemOutputs("7x gtceu:tantalum_pentoxide_dust")
        .outputFluids("gtceu:steam 800000")
        .EUt(GTValues.VHA[GTValues.HV])
        .duration(220)
        .blastFurnaceTemp(1800)
    event.recipes.gtceu.electric_blast_furnace("kubejs:niobium_tantalum/calcinate_niobium")
        .itemInputs("12x gtceu:niobium_pentoxide_hydrate_dust")
        .itemOutputs("7x gtceu:niobium_pentoxide_dust")
        .outputFluids("gtceu:steam 800000")
        .EUt(GTValues.VHA[GTValues.HV])
        .duration(220)
        .blastFurnaceTemp(1800)
})