ServerEvents.recipes(event => {
    // Titanium line
    // Brookite/Anatase into TiCl4 (same as rutile)
    event.recipes.gtceu.chemical_reactor("kubejs:titanium/brookite_to_ticl4")
        .itemInputs("2x gtceu:carbon_dust", "1x gtceu:brookite_dust", )
        .inputFluids("gtceu:chlorine 4000")
        .outputFluids("gtceu:carbon_monoxide 2000", "gtceu:titanium_tetrachloride 1000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(400)
    event.recipes.gtceu.chemical_reactor("kubejs:titanium/anatase_to_ticl4")
        .itemInputs("2x gtceu:carbon_dust", "1x gtceu:anatase_dust", )
        .inputFluids("gtceu:chlorine 4000")
        .outputFluids("gtceu:carbon_monoxide 2000", "gtceu:titanium_tetrachloride 1000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(400)

    // Simple titanium ores (similar to ilmenite) 
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/wangxibinite_decompose")
        .itemInputs("2x gtceu:wangxibinite_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("gtceu:wrought_iron_ingot", "3x gtceu:rutile_dust")
        .duration(800).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/toledoite_decompose")
        .itemInputs("3x gtceu:toledoite_dust")
        .inputFluids("gtceu:oxygen 4000")
        .itemOutputs("gtceu:wrought_iron_ingot", "3x gtceu:rutile_dust", "3x gtceu:silicon_dioxide_dust")
        .duration(800).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/florenskyite_decompose")
        .itemInputs("3x gtceu:florenskyite_dust")
        .inputFluids("gtceu:oxygen 4000")
        .itemOutputs("gtceu:wrought_iron_ingot", "3x gtceu:rutile_dust", "5x gtceu:phosphate_dust")
        .duration(800).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/hongquiite_decompose")
        .itemInputs("2x gtceu:hongquiite_dust")
        .inputFluids("gtceu:oxygen 1000")
        .itemOutputs("3x gtceu:rutile_dust")
        .duration(800).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/magneliite_decompose")
        .itemInputs("11x gtceu:magneliite_dust")
        .inputFluids("gtceu:oxygen 1000")
        .itemOutputs("12x gtceu:rutile_dust")
        .duration(800).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/ulvospinel_decompose")
        .itemInputs("7x gtceu:ulvospinel_dust", "gtceu:carbon_dust")
        .itemOutputs("2x gtceu:wrought_iron_ingot", "3x gtceu:rutile_dust")
        .outputFluids("gtceu:carbon_dioxide 1000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/griffinite_decompose")
        .itemInputs("8x gtceu:griffinite_dust", "3x gtceu:carbon_dust")
        .itemOutputs("2x gtceu:aluminium_ingot", "3x gtceu:rutile_dust")
        .outputFluids("gtceu:carbon_monoxide 3000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/heamanite_ce_decompose")
        .itemInputs("20x gtceu:heamanite_ce_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("12x gtceu:rutile_dust", "6x gtceu:potash_dust", "6x gtceu:ceria_dust")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/perovskite_decompose")
        .itemInputs("5x gtceu:perovskite_dust", "gtceu:carbon_dust")
        .itemOutputs("1x gtceu:quicklime_dust", "3x gtceu:rutile_dust")
        .outputFluids("gtceu:carbon_monoxide 1000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/macedonite_decompose")
        .itemInputs("5x gtceu:macedonite_dust", "gtceu:carbon_dust")
        .itemOutputs("1x gtceu:lead_ingot", "3x gtceu:rutile_dust")
        .outputFluids("gtceu:carbon_dioxide 1000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/loparite_decompose")
        .itemInputs("10x gtceu:loparite_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 1000")
        .itemOutputs("1x gtceu:rare_earth_dust", "6x gtceu:rutile_dust", "6x gtceu:soda_ash_dust")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/tantalaeschynite_ce_decompose")
        .itemInputs("16x gtceu:tantalaeschynite_ce_dust", "gtceu:carbon_dust")
        .itemOutputs("3x gtceu:ceria_dust", "3x gtceu:rutile_dust", "4x gtceu:tantalum_pentoxide_dust") // Not fully accurate on the oxygen or tantalum ratios, but I don't want to have to introduce another tantalum oxide just for this.
        .outputFluids("gtceu:carbon_dioxide 1000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/aeschynite_nd_decompose")
        .itemInputs("18x gtceu:aeschynite_nd_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("5x gtceu:neodymia_dust", "6x gtceu:rutile_dust", "7x gtceu:niobium_pentoxide_dust")
        .outputFluids("gtceu:carbon_dioxide 1000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/aeschynite_ce_decompose")
        .itemInputs("18x gtceu:aeschynite_ce_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("5x gtceu:cerium_trioxide_dust", "6x gtceu:rutile_dust", "7x gtceu:niobium_pentoxide_dust")
        .outputFluids("gtceu:carbon_dioxide 1000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/aeschynite_y_decompose")
        .itemInputs("18x gtceu:aeschynite_y_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("5x gtceu:yttria_dust", "6x gtceu:rutile_dust", "7x gtceu:niobium_pentoxide_dust")
        .outputFluids("gtceu:carbon_dioxide 1000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/tivanite_decompose")
        .itemInputs("14x gtceu:tivanite_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("7x gtceu:vanadium_pentoxide_dust", "6x gtceu:rutile_dust")
        .outputFluids("gtceu:steam 9600")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/brannerite_decompose")
        .itemInputs("9x gtceu:brannerite_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("3x gtceu:uraninite_dust", "6x gtceu:rutile_dust")
        .outputFluids("gtceu:carbon_dioxide 1000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/zirconolite_decompose")
        .itemInputs("11x gtceu:zirconolite_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("2x gtceu:quicklime_dust", "3x gtceu:zirconia_dust", "6x gtceu:rutile_dust")
        .outputFluids("gtceu:carbon_dioxide 1000")
        .duration(3200).EUt(GTValues.VA[GTValues.EV]).blastFurnaceTemp(2400)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/carmeltazite_decompose")
        .itemInputs("11x gtceu:carmeltazite_dust")
        .inputFluids("gtceu:oxygen 6000")
        .itemOutputs("3x gtceu:zirconia_dust", "2x gtceu:aluminium_ingot", "12x gtceu:rutile_dust")
        .duration(3200).EUt(GTValues.VA[GTValues.EV]).blastFurnaceTemp(2400)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/mannardite_decompose")
        .itemInputs("25x gtceu:mannardite_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("1x gtceu:barium_dust", "18x gtceu:rutile_dust", "7x gtceu:vanadium_pentoxide_dust")
        .outputFluids("gtceu:carbon_monoxide 1000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/priderite_decompose")
        .itemInputs("50x gtceu:priderite_dust", "gtceu:carbon_dust")
        .itemOutputs("3x gtceu:potash_dust", "42x gtceu:rutile_dust", "7x gtceu:vanadium_pentoxide_dust", "2x gtceu:wrought_iron_ingot")
        .outputFluids("gtceu:carbon_dioxide 1000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/sabinaite_decompose")
        .itemInputs("33x gtceu:sabinaite_dust")
        .inputFluids("gtceu:oxygen 4000")
        .itemOutputs("12x gtceu:soda_ash_dust", "6x gtceu:zirconia_dust", "3x gtceu:rutile_dust")
        .outputFluids("gtceu:carbon_dioxide 2000")
        .duration(3200).EUt(GTValues.VA[GTValues.EV]).blastFurnaceTemp(2400)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/zircosulfate_decompose")
        .itemInputs("14x gtceu:zircosulfate_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("3x gtceu:zirconia_dust", "3x gtceu:rutile_dust")
        .outputFluids("gtceu:sulfuric_acid 4000")
        .duration(3200).EUt(GTValues.VA[GTValues.EV]).blastFurnaceTemp(2400)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/calamaite_decompose")
        .itemInputs("8x gtceu:calamaite_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("6x gtceu:sodium_bicarbonate_dust", "3x gtceu:rutile_dust")
        .outputFluids("gtceu:sulfuric_acid 2000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/hochleitnerite_decompose")
        .itemInputs("35x gtceu:hochleitnerite_dust")
        .itemOutputs("2x gtceu:manganese_ingot", "9x gtceu:rutile_dust", "56x gtceu:phosphorus_pentoxide_dust")
        .outputFluids("gtceu:steam 153600")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/rubinite_decompose")
        .itemInputs("20x gtceu:rubinite_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("6x gtceu:quicklime_dust", "6x gtceu:rutile_dust", "9x gtceu:silicon_dioxide_dust")
        .outputFluids("gtceu:carbon_monoxide 1000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/titanite_decompose")
        .itemInputs("8x gtceu:titanite_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("5x gtceu:calcite_dust", "3x gtceu:rutile_dust", "3x gtceu:silicon_dioxide_dust")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/matsubaraite_decompose")
        .itemInputs("35x gtceu:matsubaraite_dust", "2x gtceu:carbon_dust")
        .itemOutputs("4x gtceu:strontium_dust", "15x gtceu:rutile_dust", "12x gtceu:silicon_dioxide_dust")
        .outputFluids("gtceu:carbon_dioxide 2000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/benitoite_decompose")
        .itemInputs("14x gtceu:benitoite_dust", "gtceu:carbon_dust")
        .itemOutputs("1x gtceu:barium_dust", "3x gtceu:rutile_dust", "9x gtceu:silicon_dioxide_dust")
        .outputFluids("gtceu:carbon_monoxide 1000")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/korobitsynite_decompose")
        .itemInputs("25x gtceu:korobitsynite_dust", "3x gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 6000")
        .itemOutputs("18x gtceu:sodium_bicarbonate_dust", "6x gtceu:rutile_dust", "12x gtceu:silicon_dioxide_dust")
        .outputFluids("gtceu:steam 28800")
        .duration(1600).EUt(GTValues.VA[GTValues.HV]).blastFurnaceTemp(1700)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/kosnarite_decompose")
        .itemInputs("12x gtceu:kosnarite_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 46000")
        .itemOutputs("3x gtceu:potash_dust", "12x gtceu:zirconia_dust", "84x gtceu:phosphorus_pentoxide_dust")
        .outputFluids("gtceu:carbon_monoxide 1000")
        .duration(3200).EUt(GTValues.VA[GTValues.EV]).blastFurnaceTemp(2400)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/zircon_decompose")
        .itemInputs("6x gtceu:zircon_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("3x gtceu:zirconia_dust", "3x gtceu:silicon_dioxide_dust")
        .outputFluids("gtceu:carbon_dioxide 1000")
        .duration(3200).EUt(GTValues.VA[GTValues.EV]).blastFurnaceTemp(2400)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/hafnon_decompose")
        .itemInputs("6x gtceu:hafnon_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("3x gtceu:hafnia_dust", "3x gtceu:silicon_dioxide_dust")
        .outputFluids("gtceu:carbon_dioxide 1000")
        .duration(3200).EUt(GTValues.VA[GTValues.LuV]).blastFurnaceTemp(4000)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/gittinsite_decompose")
        .itemInputs("11x gtceu:gittinsite_dust", "gtceu:carbon_dust")
        .itemOutputs("5x gtceu:calcite_dust", "3x gtceu:zirconia_dust", "6x gtceu:silicon_dioxide_dust")
        .duration(3200).EUt(GTValues.VA[GTValues.EV]).blastFurnaceTemp(2400)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/bazirite_decompose")
        .itemInputs("14x gtceu:bazirite_dust", "gtceu:carbon_dust")
        .itemOutputs("1x gtceu:barium_dust", "3x gtceu:zirconia_dust", "9x gtceu:silicon_dioxide_dust")
        .outputFluids("gtceu:carbon_monoxide 1000")
        .duration(3200).EUt(GTValues.VA[GTValues.EV]).blastFurnaceTemp(2400)
    event.recipes.gtceu.electric_blast_furnace("kubejs:titanium/armstrongite_decompose")
        .itemInputs("26x gtceu:armstrongite_dust", "gtceu:carbon_dust")
        .itemOutputs("5x gtceu:calcite_dust", "3x gtceu:zirconia_dust", "18x gtceu:silicon_dioxide_dust")
        .outputFluids("gtceu:steam 28800")
        .duration(3200).EUt(GTValues.VA[GTValues.EV]).blastFurnaceTemp(2400)

    // Remaining (complex) titanium ores
    event.recipes.gtceu.ore_digestion("kubejs:titanium/botuobinskite_digestion")
        .itemInputs("62x gtceu:botuobinskite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("1x gtceu:strontium_dust", "5x gtceu:hematite_dust", "4x gtceu:magnesia_dust", "24x gtceu:chromium_trioxide_dust", "36x gtceu:titanium_dioxide_mix_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/lakargiite_digestion")
        .itemInputs("20x gtceu:lakargiite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("8x gtceu:quicklime_dust", "6x gtceu:zirconia_dust", "3x gtceu:cassiterite_dust", "3x gtceu:titanium_dioxide_mix_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/panguite_digestion")
        .itemInputs("30x gtceu:panguite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("9x gtceu:titanium_dioxide_mix_dust", "8x gtceu:corundum_dust", "5x gtceu:scandia_dust", "4x gtceu:magnesia_dust", "3x gtceu:zirconia_dust", "2x gtceu:quicklime_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/lindsleyite_digestion")
        .itemInputs("120x gtceu:lindsleyite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("1x gtceu:barium_dust", "1x gtceu:strontium_dust", "3x gtceu:zirconia_dust", "2x gtceu:quicklime_dust", "20x gtceu:hematite_dust", "7x gtceu:magnetite_dust", 
            "2x gtceu:magnesia_dust", "48x gtceu:titanium_dioxide_mix_dust", "48x gtceu:chromium_trioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/loveringite_digestion")
        .itemInputs("240x gtceu:loveringite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("4x gtceu:quicklime_dust", "3x gtceu:ceria_dust", "3x gtceu:lanthana_dust", "65x gtceu:hematite_dust", "10x gtceu:magnesia_dust",
            "90x gtceu:titanium_dioxide_mix_dust", "48x gtceu:chromium_trioxide_dust", "20x gtceu:corundum_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/davidite_la_digestion")
        .itemInputs("144x gtceu:davidite_la_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("5x gtceu:lanthana_dust", "3x gtceu:yttria_dust", "3x gtceu:uraninite_dust", "35x gtceu:hematite_dust", "36x gtceu:titanium_dioxide_mix_dust",
            "32x gtceu:chromium_trioxide_dust", "21x gtceu:vanadium_pentoxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .outputFluids("gtceu:hydrofluoric_acid 12000")
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/davidite_ce_digestion")
        .itemInputs("144x gtceu:davidite_ce_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("6x gtceu:ceria_dust", "3x gtceu:yttria_dust", "3x gtceu:uraninite_dust", "35x gtceu:hematite_dust", "36x gtceu:titanium_dioxide_mix_dust",
            "32x gtceu:chromium_trioxide_dust", "21x gtceu:vanadium_pentoxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .outputFluids("gtceu:hydrofluoric_acid 12000")
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/davidite_y_digestion")
        .itemInputs("359x gtceu:davidite_y_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("5x gtceu:lanthana_dust", "3x gtceu:ceria_dust", "4x gtceu:sodium_peroxide_dust", "1x gtceu:quicklime_dust",
            "2x gtceu:massicot_dust", "8x gtceu:yttria_dust", "80x gtceu:hematite_dust", "12x gtceu:pyrolusite_dust", "174x gtceu:titanium_dioxide_mix_dust", 
            "63x gtceu:niobium_pentoxide_dust", "30x gtceu:zirconia_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/kangite_digestion")
        .itemInputs("40x gtceu:kangite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("13x gtceu:scandia_dust", "9x gtceu:titanium_dioxide_mix_dust", "8x gtceu:corundum_dust", "6x gtceu:zirconia_dust", "4x gtceu:magnesia_dust",
            "2x gtceu:quicklime_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/uranopolycrase_digestion")
        .itemInputs("18x gtceu:uranopolycrase_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("3x gtceu:uraninite_dust", "3x gtceu:yttria_dust", "9x gtceu:titanium_dioxide_mix_dust", "4x gtceu:niobium_pentoxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/euxenite_y_digestion")
        .itemInputs("54x gtceu:euxenite_y_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("5x gtceu:yttria_dust", "2x gtceu:quicklime_dust", "3x gtceu:ceria_dust", "3x gtceu:uraninite_dust", "1x gtceu:thorium_232_dust", 
            "25x gtceu:niobium_pentoxide_dust", "11x gtceu:tantalum_pentoxide_dust", "6x gtceu:titanium_dioxide_mix_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/thorutite_digestion")
        .itemInputs("46x gtceu:thorutite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("2x gtceu:thorium_dust", "3x gtceu:uraninite_dust", "2x gtceu:quicklime_dust", "24x gtceu:titanium_dioxide_mix_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/stefanweissite_digestion")
        .itemInputs("44x gtceu:stefanweissite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("9x gtceu:ceria_dust", "12x gtceu:zirconia_dust", "7x gtceu:niobium_pentoxide_dust", "12x gtceu:titanium_dioxide_mix_dust",
            "5x gtceu:hematite_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .outputFluids("gtceu:ree_sulfate_sludge 500")
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/laachite_digestion")
        .itemInputs("22x gtceu:laachite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("2x gtceu:quicklime_dust", "3x gtceu:pyrolusite_dust", "6x gtceu:zirconia_dust", "7x gtceu:niobium_pentoxide_dust",
            "3x gtceu:titanium_dioxide_mix_dust", "3x gtceu:hematite_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/tazzoliite_digestion")
        .itemInputs("36x gtceu:tazzoliite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("18x gtceu:barite_dust", "3x gtceu:sodium_hydroxide_dust", "6x gtceu:titanium_dioxide_mix_dust", "11x gtceu:niobium_pentoxide_dust",
            "3x gtceu:silicon_dioxide_dust", "5x gtceu:phosphate_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/asbecasite_digestion")
        .itemInputs("80x gtceu:asbecasite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("12x gtceu:quicklime_dust", "3x gtceu:titanium_dioxide_mix_dust", "3x gtceu:cassiterite_dust", "8x gtceu:beryllium_oxide_dust",
            "30x gtceu:arsenic_trioxide_dust", "12x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/bianchiniite_digestion")
        .itemInputs("20x gtceu:bianchiniite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("12x gtceu:barite_dust", "3x gtceu:titanium_dioxide_mix_dust", "5x gtceu:vanadate_dust", "10x gtceu:arsenic_trioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .outputFluids("gtceu:hydrofluoric_acid 1000")
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/azoproite_digestion")
        .itemInputs("36x gtceu:azoproite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("12x gtceu:magnesia_dust", "5x gtceu:hematite_dust", "7x gtceu:magnetite_dust", "3x gtceu:titanium_dioxide_mix_dust", "16x gtceu:borate_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/lehmannite_digestion")
        .itemInputs("85x gtceu:lehmannite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("10x gtceu:salt_dust", "2x gtceu:villiaumite_dust", "18x gtceu:sodium_hydroxide_dust", "24x gtceu:cupric_oxide_dust", "3x gtceu:titanium_dioxide_mix_dust",
            "20x gtceu:arsenic_trioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/sperlingite_digestion")
        .itemInputs("29x gtceu:sperlingite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("3x gtceu:potassium_hydroxide_dust", "3x gtceu:pyrolusite_dust", "4x gtceu:yellow_limonite_dust", "5x gtceu:corundum_dust",
            "3x gtceu:titanium_dioxide_mix_dust", "4x gtceu:phosphate_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .outputFluids("minecraft:water 14000")
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/tranquillityite_digestion")
        .itemInputs("40x gtceu:tranquillityite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("7x gtceu:magnetite_dust", "5x gtceu:hematite_dust", "6x gtceu:quicklime_dust", "3x gtceu:zirconia_dust", "9x gtceu:titanium_dioxide_mix_dust",
            "9x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/bortolanite_digestion")
        .itemInputs("30x gtceu:bortolanite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("3x gtceu:fluorite_dust", "6x gtceu:quicklime_dust", "3x gtceu:zirconia_dust", "2x gtceu:villiaumite_dust", "3x gtceu:sodium_hydroxide_dust",
            "3x gtceu:titanium_dioxide_mix_dust", "12x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/roumaite_digestion")
        .itemInputs("57x gtceu:roumaite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("3x gtceu:fluorite_dust", "12x gtceu:quicklime_dust", "8x gtceu:villiaumite_dust", "4x gtceu:niobium_pentoxide_dust",
            "3x gtceu:titanium_dioxide_mix_dust", "24x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .outputFluids("gtceu:ree_sulfate_sludge 1000")
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/kochite_digestion")
        .itemInputs("30x gtceu:kochite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("6x gtceu:villiaumite_dust", "4x gtceu:quicklime_dust", "3x gtceu:pyrolusite_dust", "3x gtceu:zirconia_dust",
            "3x gtceu:titanium_dioxide_mix_dust", "12x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/saamite_digestion")
        .itemInputs("33x gtceu:saamite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("6x gtceu:barite_dust", "2x gtceu:villiaumite_dust", "6x gtceu:sodium_hydroxide_dust", "6x gtceu:titanium_dioxide_mix_dust",
            "4x gtceu:niobium_pentoxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/epistolite_digestion")
        .itemInputs("35x gtceu:epistolite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("12x gtceu:sodium_hydroxide_dust", "7x gtceu:niobium_pentoxide_dust", "3x gtceu:titanium_dioxide_mix_dust",
            "12x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/innelite_digestion")
        .itemInputs("68x gtceu:innelite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("48x gtceu:barite_dust", "18x gtceu:titanium_dioxide_mix_dust", "9x gtceu:sodium_hydroxide_dust", "7x gtceu:sodium_bisulfate_dust",
            "6x gtceu:pyrolusite_dust", "5x gtceu:phosphate_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/polyphite_digestion")
        .itemInputs("29x gtceu:polyphite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("4x gtceu:villiaumite_dust", "21x gtceu:sodium_hydroxide_dust", "6x gtceu:titanium_dioxide_mix_dust", "6x gtceu:silicon_dioxide_dust",
            "15x gtceu:phosphate_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/bussenite_digestion")
        .itemInputs("26x gtceu:bussenite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("6x gtceu:sodium_bicarbonate_dust", "2x gtceu:villiaumite_dust", "12x gtceu:barite_dust", "4x gtceu:yellow_limonite_dust", "3x gtceu:titanium_dioxide_mix_dust",
            "6x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/hezuolinite_digestion")
        .itemInputs("35x gtceu:hezuolinite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("3x gtceu:strontium_dust", "3x gtceu:zirconia_dust", "9x gtceu:titanium_dioxide_mix_dust", "3x gtceu:hematite_dust", "12x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .outputFluids("gtceu:ree_sulfate_sludge 500")
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/orthojoaquinite_la_digestion")
        .itemInputs("45x gtceu:orthojoaquinite_la_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("3x gtceu:sodium_hydroxide_dust", "12x gtceu:barite_dust", "5x gtceu:lanthana_dust", "4x gtceu:yellow_limonite_dust", "6x gtceu:titanium_dioxide_mix_dust",
            "24x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/orthojoaquinite_ce_digestion")
        .itemInputs("45x gtceu:orthojoaquinite_ce_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("3x gtceu:sodium_hydroxide_dust", "12x gtceu:barite_dust", "6x gtceu:ceria_dust", "4x gtceu:yellow_limonite_dust", "6x gtceu:titanium_dioxide_mix_dust",
            "24x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/joaquinite_ce_digestion")
        .itemInputs("44x gtceu:joaquinite_ce_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("2x gtceu:villiaumite_dust", "12x gtceu:barite_dust", "6x gtceu:ceria_dust", "3x gtceu:hematite_dust", "6x gtceu:titanium_dioxide_mix_dust",
            "24x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/strontiojoaquinite_digestion")
        .itemInputs("46x gtceu:strontiojoaquinite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("2x gtceu:strontium_dust", "12x gtceu:barite_dust", "3x gtceu:sodium_hydroxide_dust", "4x gtceu:yellow_limonite_dust", "6x gtceu:titanium_dioxide_mix_dust",
            "24x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/lovozerite_digestion")
        .itemInputs("66x gtceu:lovozerite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("12x gtceu:sodium_hydroxide_dust", "4x gtceu:quicklime_dust", "3x gtceu:zirconia_dust", "3x gtceu:titanium_dioxide_mix_dust", "36x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/labyrinthite_digestion")
        .itemInputs("267x gtceu:labyrinthite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("6x gtceu:salt_dust", "42x gtceu:sodium_hydroxide_dust", "15x gtceu:potash_dust", "8x gtceu:strontium_dust", "24x gtceu:quicklime_dust",
            "7x gtceu:magnetite_dust", "18x gtceu:zirconia_dust", "3x gtceu:titanium_dioxide_mix_dust", "153x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/dualite_digestion")
        .itemInputs("263x gtceu:dualite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("4x gtceu:salt_dust", "102x gtceu:sodium_hydroxide_dust", "14x gtceu:quicklime_dust", "3x gtceu:ceria_dust", "1x gtceu:strontium_dust",
            "6x gtceu:pyrolusite_dust", "4x gtceu:yellow_limonite_dust", "12x gtceu:titanium_dioxide_mix_dust", "9x gtceu:zirconia_dust", "153x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/grossmanite_digestion")
        .itemInputs("10x gtceu:grossmanite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("2x gtceu:quicklime_dust", "3x gtceu:titanium_dioxide_mix_dust", "3x gtceu:corundum_dust", "3x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/astrophyllite_digestion")
        .itemInputs("39x gtceu:astrophyllite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("3x gtceu:potash_dust", "2x gtceu:villiaumite_dust", "7x gtceu:magnetite_dust", "16x gtceu:yellow_limonite_dust", "6x gtceu:titanium_dioxide_mix_dust",
            "12x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/umbite_digestion")
        .itemInputs("32x gtceu:umbite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("6x gtceu:potash_dust", "3x gtceu:zirconia_dust", "3x gtceu:titanium_dioxide_mix_dust", "18x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/senkevichite_digestion")
        .itemInputs("34x gtceu:senkevichite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("1x gtceu:caesium_dust", "3x gtceu:potassium_hydroxide_dust", "3x gtceu:sodium_hydroxide_dust", "4x gtceu:quicklime_dust", 
            "3x gtceu:titanium_dioxide_mix_dust", "21x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/jonesite_digestion")
        .itemInputs("64x gtceu:jonesite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("24x gtceu:barite_dust", "3x gtceu:potassium_hydroxide_dust", "3x gtceu:sodium_hydroxide_dust", "12x gtceu:titanium_dioxide_mix_dust",
            "5x gtceu:corundum_dust", "30x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .outputFluids("minecraft:water 5000")
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/neptunite_digestion")
        .itemInputs("40x gtceu:neptunite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("3x gtceu:potassium_hydroxide_dust", "6x gtceu:sodium_hydroxide_dust", "1x gtceu:lithium_dust", "5x gtceu:hematite_dust",
            "6x gtceu:titanium_dioxide_mix_dust", "24x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/qeltite_digestion")
        .itemInputs("23x gtceu:qeltite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("6x gtceu:quicklime_dust", "3x gtceu:titanium_dioxide_mix_dust", "9x gtceu:silicon_dioxide_dust", "5x gtceu:hematite_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/rippite_digestion")
        .itemInputs("22x gtceu:rippite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("3x gtceu:potassium_hydroxide_dust", "2x gtceu:carobbiite_dust", "4x gtceu:niobium_pentoxide_dust", "3x gtceu:titanium_dioxide_mix_dust", 
            "12x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/burpalite_digestion")
        .itemInputs("15x gtceu:burpalite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("4x gtceu:villiaumite_dust", "2x gtceu:quicklime_dust", "3x gtceu:zirconia_dust", "6x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/oneillite_digestion")
        .itemInputs("133x gtceu:oneillite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("2x gtceu:salt_dust", "42x gtceu:sodium_hydroxide_dust", "6x gtceu:quicklime_dust", "9x gtceu:pyrolusite_dust", "7x gtceu:magnetite_dust",
            "9x gtceu:zirconia_dust", "4x gtceu:niobium_pentoxide_dust", "75x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/aqualite_digestion")
        .itemInputs("141x gtceu:aqualite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("2x gtceu:salt_dust", "6x gtceu:sodium_hydroxide_dust", "3x gtceu:potassium_hydroxide_dust", "1x gtceu:strontium_dust", "30x gtceu:calcium_hydroxide_dust",
            "9x gtceu:zirconia_dust", "78x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .outputFluids("minecraft:water 8000")
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])
    event.recipes.gtceu.ore_digestion("kubejs:titanium/lemoynite_digestion")
        .itemInputs("46x gtceu:lemoynite_dust")
        .inputFluids("minecraft:water 2000")
        .chancedFluidInput("gtceu:nitric_acid", 3000, 0)
        .chancedFluidInput("gtceu:sulfuric_acid", 3000, 0)
        .itemOutputs("3x gtceu:sodium_hydroxide_dust", "3x gtceu:potassium_hydroxide_dust", "5x gtceu:calcium_hydroxide_dust", "6x gtceu:zirconia_dust",
            "30x gtceu:silicon_dioxide_dust")
        .chancedFluidOutput("gtceu:dilute_nitric_acid 2000", 3000, 0)
        .chancedFluidOutput("gtceu:diluted_sulfuric_acid 2000", 3000, 0)
        .outputFluids("minecraft:water 3000")
        .duration(1800).EUt(GTValues.VHA[GTValues.IV])

    // Zirconium/Hafnium sublines
    event.recipes.gtceu.chemical_reactor("kubejs:zirconium/zirconia_to_tetrachloride")
        .itemInputs("2x gtceu:carbon_dust", "3x gtceu:zirconia_dust")
        .inputFluids("gtceu:chlorine 4000")
        .itemOutputs("5x gtceu:zirconium_tetrachloride_dust")
        .outputFluids("gtceu:carbon_monoxide 2000")
        .duration(400).EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.large_chemical_reactor("kubejs:zirconium/hafnium_to_tetraiodide")
        .itemInputs("2x gtceu:carbon_dust", "3x gtceu:hafnia_dust", "4x gtceu:iodine_dust")
        .itemOutputs("5x gtceu:hafnium_tetraiodide_dust")
        .outputFluids("gtceu:carbon_monoxide 2000")
        .duration(400).EUt(GTValues.VA[GTValues.IV])
    event.recipes.gtceu.electric_blast_furnace("kubejs:zirconium/zirconium_tetrachloride_to_metal")
        .itemInputs("5x gtceu:zirconium_tetrachloride_dust", "4x gtceu:lithium_dust")
        .itemOutputs("1x gtceu:hot_zirconium_ingot", "8x gtceu:lithium_chloride_dust")
        .duration(800).EUt(GTValues.VA[GTValues.IV]).blastFurnaceTemp(5200)
    event.recipes.gtceu.electric_blast_furnace("kubejs:zirconium/hafnium_tetraiodide_to_metal")
        .itemInputs("5x gtceu:hafnium_tetraiodide_dust", "2x gtceu:samarium_dust")
        .itemOutputs("1x gtceu:hot_hafnium_ingot", "6x gtceu:samarium_iodide_dust")
        .duration(800).EUt(GTValues.VA[GTValues.LuV]).blastFurnaceTemp(6600)
})