# Configuration Toggles for Multiblocks
Multiblocks:
  # Whether the Robust Alloy Materializer is Enabled
  # Default = True
  RobustAlloyMaterializer: true

  # Whether the Large Cracking Machine is Enabled
  # Default = True
  LargeCrackingMachine: true

  # Whether the Synthesis Vessel is Enabled
  # Default = True
  SynthesisVessel: true

  # Whether the Large Pyrolysis Oven is Enabled
  # Default = True
  LargePyrolysisOven: true

  # Whether the Advanced Fusion Reactors are Enabled
  # Default = True
  AdvancedFusionReactors: true

  # Whether the Compact Assembly Line is Enabled
  # Tip: Controller recipe should contain 4 Assembly Line controllers
  # Default = True
  CompactAssemblyLine: true

  # Whether the Rock Processing Plant is Enabled
  # Tip: Controller recipe should contain a macerator, a centrifuge and an electrolyzer
  # Default = True
  RockProcessingPlant: true

  # Whether the Industrial Greenhouse is Enabled
  # Default = True
  IndustrialGreenhouse: true

  # Whether the Tree Growing Chamber is Enabled
  # Default = True
  TreeGrowingChamber: true

  # Whether the Disassembler is enabled
  # §cWarning: §rUniversal Circuits MUST be enabled
  # otherwise it could lead to some issues with recipes
  # Default = True
  Disassembler: true

# Configuration Toggles for Optical Features
OpticalMachines:
  # Whether the Expanded Data Access Hatches are Enabled
  # Default = True
  ExpandedDataAccessHatches: true

  # Whether the Wireless Optical Hatches & Cloud Transmission Database are Enabled
  # Default = True
  WirelessOptical: true

  # Whether the Expanded Data Bank is Enabled
  # Default = True
  ExpandedDatabank: true

  # Whether the Optical Tranmission Network is Enabled
  # Default = True
  OpticalTransmissionNetwork: true

# Whether the Universal Circuits are Enabled.
UniversalCircuits: true

