# Configuration Toggles for Multiblocks
Multiblocks:
  # Whether the Robust Alloy Materializer is Enabled
  # Default = True
  RobustAlloyMaterializer: true

  # Whether the Large Cracking Machine is Enabled
  # Default = True
  LargeCrackingMachine: true

  # Whether the Synthesis Vessel is Enabled
  # Default = True
  SynthesisVessel: true

  # Whether the Large Pyrolysis Oven is Enabled
  # Default = True
  LargePyrolysisOven: true

  # Whether the Compact Assembly Line is Enabled
  # Tip: Controller recipe should contain 4 Assembly Line controllers
  # Default = True
  CompactAssemblyLine: true

  # Whether the Rock Processing Plant is Enabled
  # Tip: Controller recipe should contain a large macerator, a large centrifuge and an large electrolyzer
  # Default = True
  RockProcessingPlant: true

  # Whether the Industrial Greenhouse is Enabled
  # Default = True
  IndustrialGreenhouse: true

  # Whether the Tree Growing Chamber is Enabled
  # Default = True
  TreeGrowingChamber: true

  # Whether the Disassembler is enabled
  # §cUniversal Circuits MUST be enabled
  # Default = True
  Disassembler: true

  # Whether the Large Air Collector is Enabled
  # Default = True
  LargeGasCollector: true

  # Whether the Expanded Data Bank is Enabled
  # Default = True
  ExpandedDatabank: true

  # Whether the Matrix Data Relay is Enabled
  # §cRequires Wireless Optical Hatches enabled
  # Default = True
  MatrixDataRelay: true

# Configuration Toggles for Normal Machines
RegularMachines:
  # Whether the Expanded Data Access Hatches are Enabled
  # Default = True
  ExpandedDataAccessHatches: true

  # Whether the Wireless Optical Hatches are Enabled
  # Default = True
  WirelessOpticalHatches: true

  # Whether the Configurable Cleaning Maintenance Hatch is Enabled
  # Default = True
  CCMHatch: true

# Whether the Universal Circuits are Enabled.
UniversalCircuits: true

