#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Sep 21 19:00:45 CEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=16
shaderPack=photon_v1.3b.zip
