ServerEvents.tags("item", event => {
    // Attempt 2 at hiding excess GT ore permutations
    event.add("c:hidden_from_recipe_viewers", /^gtceu:granite_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:diorite_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:red_granite_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:andesite_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:marble_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:deepslate_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:tuff_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:sand_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:red_sand_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:gravel_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:basalt_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:netherrack_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:blackstone_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:endstone_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)

    event.add("c:hidden_from_recipe_viewers", /^gtceu:deepstone_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:depthrock_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:shiverstone_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:honeycomb_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:red_deepstone_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:sculk_stone_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:sculk_grime_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:gloomslate_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:mushroomy_deepstone_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:fourth_layer_deepstone_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:deep_prismarine_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:packed_ice_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:blue_ice_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:seventh_layer_deepstone_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:travertine_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:chert_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:kaolin_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:sandy_soil_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:chalk_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:argillite_[a-z0-9]+(?:_+[a-z0-9]+)*_ore$/)

    // Hide other items
    event.add("c:hidden_from_recipe_viewers", "crazyae2addons:research_fluid")
    event.add("c:hidden_from_recipe_viewers", "advanced_ae:quantum_infusion")
    event.add("c:hidden_from_recipe_viewers", "cb_microblock:microblock")
    event.add("c:hidden_from_recipe_viewers", /^"cb_microblock:microblock"$/)
    event.add("c:hidden_from_recipe_viewers", /^"productivebees:spawn_egg_[a-z]*"$/)
    event.add("c:hidden_from_recipe_viewers", /^gtceu:[a-z0-9]+(?:_+[a-z0-9]+)*_indicator$/)

});