StartupEvents.registry("item", event => {
    // Earthline ion exchange resin
    event.create("ion_exchange_resin")
        .texture("kubejs:item/earthline/ion_resin_1")
        .displayName("Ion Exchange Resin")
        .maxStackSize(16)
    event.create("mixed_ree_ion_exchange_resin")
        .texture("kubejs:item/earthline/ion_resin_2")
        .displayName("Mixed Rare-Earth Rich Ion Exchange Resin")
        .maxStackSize(16)
    event.create("weighty_ion_exchange_resin")
        .texture("kubejs:item/earthline/ion_resin_3")
        .displayName("Weighty Ion Exchange Resin")
        .maxStackSize(16)
    event.create("discolored_ion_exchange_resin")
        .texture("kubejs:item/earthline/ion_resin_4")
        .displayName("Discolored Ion Exchange Resin")
        .maxStackSize(16)
    event.create("heavy_ree_ion_exchange_resin")
        .texture("kubejs:item/earthline/ion_resin_5")
        .displayName("Heavy Rare-Earth Ion Exchange Resin")
        .maxStackSize(16)
    event.create("worn_ion_exchange_resin")
        .texture("kubejs:item/earthline/ion_resin_6")
        .displayName("Worn Ion Exchange Resin")
        .maxStackSize(16)
    event.create("damaged_ion_exchange_resin")
        .texture("kubejs:item/earthline/ion_resin_7")
        .displayName("Damaged Ion Exchange Resin")
        .maxStackSize(16)
    event.create("depleted_ion_exchange_resin")
        .texture("kubejs:item/earthline/ion_resin_8")
        .displayName("Depleted Ion Exchange Resin")
        .maxStackSize(16)
})