const List = Java.loadClass("java.util.List")
const Tags = Java.loadClass("dev.latvian.mods.kubejs.util.Tags")
const LocalizationUtils = Java.loadClass("com.lowdragmc.lowdraglib.utils.LocalizationUtils")
const FusionReactorMachine = Java.loadClass("com.gregtechceu.gtceu.common.machine.multiblock.electric.FusionReactorMachine")
const CoilWorkableElectricMultiblockMachine = Java.loadClass("com.gregtechceu.gtceu.api.machine.multiblock.CoilWorkableElectricMultiblockMachine")
const $LargeTurbineMachine = Java.loadClass("com.gregtechceu.gtceu.common.machine.multiblock.generator.LargeTurbineMachine")
const RecipeLogic = Java.loadClass("com.gregtechceu.gtceu.api.machine.trait.RecipeLogic")

// Multiblock recipe categories
GTCEuStartupEvents.registry("gtceu:recipe_type", event => {
    // Ore digester
    event.create("ore_digestion")
        .category("multiblock")
        .setEUIO("in")
        .setMaxIOSize(3, 12, 3, 6)
        .setSlotOverlay(false, false, GuiTextures.ARROW_INPUT_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_MACERATE, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.CHEMICAL)

    event.create("fish_shrine")
        .category("multiblock")
        .setEUIO("in")
        .setMaxIOSize(3, 6, 1, 3)
        .setSlotOverlay(false, false, GuiTextures.ARROW_INPUT_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_LATHE, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.SCIENCE)
})

// Multiblock definitions
GTCEuStartupEvents.registry("gtceu:machine", event => {
    // Ore digester
    event.create("ore_digester", "multiblock")
        .machine((holder) => new CoilWorkableElectricMultiblockMachine(holder))
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes(["ore_digestion"])
        .recipeModifiers(
            [
                GTRecipeModifiers.PARALLEL_HATCH,  
                (machine, recipe) => GTRecipeModifiers.pyrolyseOvenOverclock(machine, recipe),
                GTRecipeModifiers.OC_NON_PERFECT, GTRecipeModifiers.BATCH_MODE
            ]
        )
        .appearanceBlock(GCYMBlocks.CASING_CORROSION_PROOF)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("A#####A", "A#####A", "AGGGGGA", "ACCCCCA", "AACCCAA", "##GCG##", "##GCG##", "###C###", "#######")
            .aisle("##SSS##", "##VVV##", "GCBBBCG", "CCIIICC", "AH J HA", "#H   H#", "#H   H#", "#CCCCC#", "#######")
            .aisle("#S   S#", "#V   V#", "GBCCCBG", "CIIIIIC", "C  J  C", "G     G", "G     G", "#CCCCC#", "###S###")
            .aisle("#S   S#", "#V   V#", "GBCCCBG", "CIIXIIC", "C  X  C", "G  X  G", "G  X  G", "CCCSCCC", "##SSS##")
            .aisle("#S   S#", "#V   V#", "GBCCCBG", "CIIIIIC", "C  J  C", "G     G", "G     G", "#CCCCC#", "###S###")
            .aisle("##SSS##", "##VVV##", "GCBBBCG", "CCIIICC", "AH J HA", "#H   H#", "#H   H#", "#CCCCC#", "#######")
            .aisle("A#####A", "A#####A", "AGGGGGA", "ACC@CCA", "AACCCAA", "##GCG##", "##GCG##", "###C###", "#######")
            .where("@", Predicates.controller(Predicates.blocks(definition.get())))
            .where("C", Predicates.blocks("gtceu:corrosion_proof_casing")
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
                .or(Predicates.autoAbilities(definition.getRecipeTypes())))
            .where("S", Predicates.blocks("gtceu:solid_machine_casing"))
            .where("V", Predicates.blocks("gtceu:invar_frame"))
            .where("A", Predicates.blocks("gtceu:hsla_steel_frame"))
            .where("G", Predicates.blocks("gtceu:laminated_glass"))
            .where("H", Predicates.heatingCoils())
            .where("B", Predicates.blocks("gtceu:titanium_firebox_casing"))
            .where("J", Predicates.blocks("gtceu:engine_intake_casing"))
            .where("X", Predicates.blocks("gtceu:titanium_gearbox"))
            .where("I", Predicates.blocks("gtceu:filter_casing"))
            .where(" ", Predicates.air())
            .where("#", Predicates.any())
            .build())
        .workableCasingModel("gtceu:block/casings/gcym/corrosion_proof_casing",
            "gtceu:block/machines/fermenter");

    // Starcatcher Shrine
    event.create("fish_shrine", "multiblock")
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes(["fish_shrine"])
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT, GTRecipeModifiers.BATCH_MODE])
        .appearanceBlock(() => Block.getBlock("gtceu:steel_turbine_casing"))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("#CCBCC#", "##F F##", "#######", "#######", "#######", "#######", "#######", "#######", "#######")
            .aisle("CAABAAC", "#AACAA#", "#FF FF#", "#F###F#", "#F###F#", "#######", "#######", "#######", "#######")
            .aisle("CAABAAC", "FAAAAAF", "#F#A#FA", "### ###", "### ###", "## G ##", "## G ##", "## G ##", "### ###")
            .aisle("BBBBBBB", " CAAAC ", "# AAA #", "##   ##", "## G ##", "# GEG #", "# GEG #", "# GEG #", "## G ##")
            .aisle("CAABAAC", "FAAAAAF", "#F#A#FA", "### ###", "### ###", "## G ##", "## G ##", "## G ##", "### ###")
            .aisle("CAABAAC", "#AA@AA#", "#FF FF#", "#F###F#", "#F###F#", "### ###", "#######", "#######", "#######")
            .aisle("#CCBCC#", "##F F##", "#######", "#######", "#######", "#######", "#######", "#######", "#######")
            .where("@", Predicates.controller(Predicates.blocks(definition.get())))
            .where("C", Predicates.blocks("gtceu:steel_turbine_casing")
                .or(Predicates.autoAbilities(definition.getRecipeTypes()))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
            )
            .where("F", Predicates.blocks("gtceu:blue_steel_frame"))
            .where("G", Predicates.blocks("gtceu:tempered_glass"))
            .where("B", Predicates.blocks("gtceu:steel_firebox_casing"))
            .where("A", Predicates.blocks("gtceu:frostproof_machine_casing"))
            .where("E", Predicates.blocks("gtceu:energetic_alloy_block"))
            .where(" ", Predicates.air())
            .where("#", Predicates.any())
            .build())
        .workableCasingModel("gtceu:block/casings/mechanic/machine_casing_turbine_steel",
            "gtceu:block/multiblock/primitive_pump")

    // Polymerizer multi
    event.create("polymer_multi", "multiblock")
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes("polymerization")
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_PERFECT_SUBTICK, GTRecipeModifiers.BATCH_MODE])
        .appearanceBlock(GCYMBlocks.CASING_REACTION_SAFE)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("FFFFCCCFFFF", "FCCCHHHCCCF", "FCCCHHHCCCF", "FFFFCCCFFFF")
            .aisle("FCCCCCCCCCF", "CPPP   PPPC", "CPPP   PPPC", "FCCCCCCCCCF")
            .aisle("FCCCCCCCCCF", "CGGG   GGGC", "CGGG   GGGC", "FCCCCCCCCCF")
            .aisle("F###C@C###F", "F###GGG###F", "F###GGG###F", "F###CCC###F")
            .where("@", Predicates.controller(Predicates.blocks(definition.get())))
            .where("C", Predicates.blocks("gtceu:reaction_safe_mixing_casing").setMinGlobalLimited(16)
                .or(Predicates.autoAbilities(definition.getRecipeTypes()))
                .or(Predicates.abilities(PartAbility.INPUT_LASER).setMaxGlobalLimited(1))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1)))
            .where("G", Predicates.blocks("gtceu:laminated_glass"))
            .where("F", Predicates.blocks("gtceu:polytetrafluoroethylene_frame"))
            .where("P", Predicates.blocks("gtceu:tungstensteel_pipe_casing"))
            .where("H", Predicates.blocks("gtceu:tungstensteel_firebox_casing"))
            .where("#", Predicates.any())
            .where(" ", Predicates.air())
            .build())
        .workableCasingModel("gtceu:block/casings/gcym/reaction_safe_mixing_casing",
            "gtceu:block/machines/polymerizer")
})