/**
 * Create Dimension Markers for other dimensions.
 * Dimension markers are the item-based icons to indicate dimensions for GregTech recipes in EMI.
 */
GTCEuStartupEvents.registry("gtceu:dimension_marker", event => {
    event.create("infinite_abyss:first_layer")
        .iconSupplier(() => Item.of("infinite_abyss:deepstone").getItem())
        .tier(0)
        .overrideName("Deep Caverns")
    event.create("undergarden:undergarden")
        .iconSupplier(() => Item.of("undergarden:mogmoss").getItem())
        .tier(0)
        .overrideName("Undergarden")
    event.create("the_bumblezone:the_bumblezone")
        .iconSupplier(() => Item.of("minecraft:honeycomb").getItem())
        .tier(0)
        .overrideName("The Bumblezone")
    event.create("twilightforest:twilight_forest")
        .iconSupplier(() => Item.of("twilightforest:twilight_portal_miniature_structure").getItem())
        .tier(0)
        .overrideName("Twilight Forest")
    event.create("infinite_abyss:second_layer")
        .iconSupplier(() => Item.of("infinite_abyss:red_deepstone").getItem())
        .tier(0)
        .overrideName("Scorched Caverns")
    event.create("deeperdarker:otherside")
        .iconSupplier(() => Item.of("deeperdarker:soul_crystal").getItem())
        .tier(0)
        .overrideName("Otherside")
    event.create("infinite_abyss:fourth_layer")
        .iconSupplier(() => Item.of("infinite_abyss:large_red_mushroom").getItem())
        .tier(0)
        .overrideName("Fungal Caverns")
    event.create("infinite_abyss:fifth_layer")
        .iconSupplier(() => Item.of("infinite_abyss:deep_prismarine").getItem())
        .tier(0)
        .overrideName("Challenger Deep")
    event.create("infinite_abyss:sixth_layer")
        .iconSupplier(() => Item.of("infinite_abyss:light_blue_crystal").getItem())
        .tier(0)
        .overrideName("Permafrost Depths")
    event.create("infinite_abyss:seventh_layer")
        .iconSupplier(() => Item.of("infinite_abyss:strange_stem_bottom").getItem())
        .tier(0)
        .overrideName("Forbidden Chasm")
})
