/**
 * Defines ore generation in other dimensions.
 */

const BlockTags = Java.loadClass("net.minecraft.tags.BlockTags")

GTCEuStartupEvents.registry("gtceu:world_gen_layer", event => {
    event.create("first_layer")
        .targets("#minecraft:overworld_carver_replaceables")
        .dimensions("infinite_abyss:first_layer")

    event.create("undergarden")
        .targets("#undergarden:depthrock_ore_replaceables", "#undergarden:shiverstone_ore_replaceables", "#undergarden:tremblecrust_ore_replaceables")
        .dimensions("undergarden:undergarden")

    event.create("the_bumblezone")
        .targets("#forge:storage_blocks/wax")
        .dimensions("the_bumblezone:the_bumblezone")

    event.create("twilightforest")
        .targets("#minecraft:stone_ore_replaceables")
        .dimensions("twilightforest:twilight_forest")

    event.create("second_layer")
        .targets("#minecraft:overworld_carver_replaceables")
        .dimensions("infinite_abyss:second_layer")

    event.create("otherside")
        .targets("#deeperdarker:blooming_pool_replaceable", "#deeperdarker:gloomslate_replaceable", "#deeperdarker:gloomy_sculk_replaceable", "#deeperdarker:sculk_stone_replaceables")
        .dimensions("deeperdarker:otherside")

    event.create("fourth_layer")
        .targets("#minecraft:overworld_carver_replaceables")
        .dimensions("infinite_abyss:fourth_layer")

    event.create("fifth_layer")
        .targets("#minecraft:overworld_carver_replaceables")
        .dimensions("infinite_abyss:fifth_layer")

    event.create("sixth_layer")
        .targets("#minecraft:overworld_carver_replaceables")
        .dimensions("infinite_abyss:sixth_layer")

    event.create("seventh_layer")
        .targets("#minecraft:overworld_carver_replaceables")
        .dimensions("infinite_abyss:seventh_layer")
})

GTCEuStartupEvents.registry("gtceu:tag_prefix", event => {
    event.create("deepstone", "ore")
        .stateSupplier(() => Block.getBlock("infinite_abyss:deepstone").defaultBlockState())
        .baseModelLocation("infinite_abyss:block/deepstone")
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .miningToolTag("minecraft:mineable/pickaxe")
        .doubleDrops(true)

    event.create("depthrock", "ore")
        .stateSupplier(() => Block.getBlock("undergarden:depthrock").defaultBlockState())
        .baseModelLocation("undergarden:block/depthrock")
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .miningToolTag("minecraft:mineable/pickaxe")
        .doubleDrops(true)
    event.create("shiverstone", "ore")
        .stateSupplier(() => Block.getBlock("undergarden:shiverstone").defaultBlockState())
        .baseModelLocation("undergarden:block/shiverstone")
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .miningToolTag("minecraft:mineable/pickaxe")
        .doubleDrops(true)
    
    event.create("honeycomb", "ore")
        .stateSupplier(() => Block.getBlock("minecraft:honeycomb_block").defaultBlockState())
        .baseModelLocation("minecraft:block/honeycomb_block")
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .miningToolTag("minecraft:mineable/pickaxe")
        .doubleDrops(true)

    // Twilight forest not necessary (?)

    event.create("red_deepstone", "ore")
        .stateSupplier(() => Block.getBlock("infinite_abyss:red_deepstone").defaultBlockState())
        .baseModelLocation("infinite_abyss:block/red_deepstone")
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .miningToolTag("minecraft:mineable/pickaxe")
        .doubleDrops(true)

    event.create("sculk_stone", "ore")
        .stateSupplier(() => Block.getBlock("deeperdarker:sculk_stone").defaultBlockState())
        .baseModelLocation("deeperdarker:block/sculk_stone")
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .miningToolTag("minecraft:mineable/pickaxe")
        .doubleDrops(true)
    event.create("sculk_grime", "ore")
        .stateSupplier(() => Block.getBlock("deeperdarker:sculk_grime").defaultBlockState())
        .baseModelLocation("deeperdarker:block/sculk_grime")
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .miningToolTag("minecraft:mineable/pickaxe")
        .doubleDrops(true)
    event.create("gloomslate", "ore")
        .stateSupplier(() => Block.getBlock("deeperdarker:gloomslate").defaultBlockState())
        .baseModelLocation("deeperdarker:block/gloomslate")
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .miningToolTag("minecraft:mineable/pickaxe")
        .doubleDrops(true)

    event.create("mushroomy_deepstone", "ore")
        .stateSupplier(() => Block.getBlock("infinite_abyss:mushroomy_deepstone").defaultBlockState())
        .baseModelLocation("infinite_abyss:block/mushroomy_deepstone")
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .miningToolTag("minecraft:mineable/pickaxe")
        .doubleDrops(true)
    event.create("fourth_layer_deepstone", "ore")
        .stateSupplier(() => Block.getBlock("infinite_abyss:fourth_layer_deepstone").defaultBlockState())
        .baseModelLocation("infinite_abyss:block/fourth_layer_deepstone")
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .miningToolTag("minecraft:mineable/pickaxe")
        .doubleDrops(true)

    event.create("deep_prismarine", "ore")
        .stateSupplier(() => Block.getBlock("infinite_abyss:deep_prismarine").defaultBlockState())
        .baseModelLocation("infinite_abyss:block/deep_prismarine")
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .miningToolTag("minecraft:mineable/pickaxe")
        .doubleDrops(true)

    event.create("packed_ice", "ore")
        .stateSupplier(() => Block.getBlock("minecraft:packed_ice").defaultBlockState())
        .baseModelLocation("minecraft:block/packed_ice")
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .miningToolTag("minecraft:mineable/pickaxe")
        .doubleDrops(true)
    event.create("blue_ice", "ore")
        .stateSupplier(() => Block.getBlock("minecraft:blue_ice").defaultBlockState())
        .baseModelLocation("minecraft:block/blue_ice")
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .miningToolTag("minecraft:mineable/pickaxe")
        .doubleDrops(true)

    event.create("seventh_layer_deepstone", "ore")
        .stateSupplier(() => Block.getBlock("infinite_abyss:seventh_layer_deepstone").defaultBlockState())
        .baseModelLocation("infinite_abyss:block/seventh_layer_deepstone")
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .miningToolTag("minecraft:mineable/pickaxe")
        .doubleDrops(true)

    // Bonus overworld ores
    event.create("travertine", "ore")
        .stateSupplier(() => Block.getBlock("natures_spirit:travertine").defaultBlockState())
        .baseModelLocation("natures_spirit:block/travertine")
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .miningToolTag("minecraft:mineable/pickaxe")
        .doubleDrops(true)
    event.create("chert", "ore")
        .stateSupplier(() => Block.getBlock("natures_spirit:chert").defaultBlockState())
        .baseModelLocation("natures_spirit:block/chert")
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .miningToolTag("minecraft:mineable/pickaxe")
        .doubleDrops(true)
    event.create("kaolin", "ore")
        .stateSupplier(() => Block.getBlock("natures_spirit:kaolin").defaultBlockState())
        .baseModelLocation("natures_spirit:block/kaolin")
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .miningToolTag("minecraft:mineable/pickaxe")
        .doubleDrops(true)
    event.create("sandy_soil", "ore")
        .stateSupplier(() => Block.getBlock("natures_spirit:sandy_soil").defaultBlockState())
        .baseModelLocation("natures_spirit:block/sandy_soil")
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .miningToolTag("minecraft:mineable/pickaxe")
        .doubleDrops(true)
    event.create("chalk", "ore")
        .stateSupplier(() => Block.getBlock("regions_unexplored:chalk").defaultBlockState())
        .baseModelLocation("regions_unexplored:block/chalk")
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .miningToolTag("minecraft:mineable/pickaxe")
        .doubleDrops(true)
    event.create("argillite", "ore")
        .stateSupplier(() => Block.getBlock("regions_unexplored:argillite").defaultBlockState())
        .baseModelLocation("regions_unexplored:block/argillite")
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .miningToolTag("minecraft:mineable/pickaxe")
        .doubleDrops(true)
})
